### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined when used with webpack 5

### ISSUE THREAD

**Issue by fengyun2** [jantimon/html-webpack-plugin#1163] opened 2019-02-14 15:02 UTC
## Expected behaviour

TypeError should not be thrown

## Current behaviour

TypeError is thrown

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.3.0
win32 10.0.14393

npm --version
6.1.0

npm ls webpack
webpack@5.0.0-alpha.10

npm ls html-webpack-plugin
html-webpack-plugin@4.0.0-beta.5
```

### Config

Copy the minimal `webpack.config.js` to produce this issue:

```js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

const nodePathParts = ['./src', './node_modules'].map(p => path.resolve(p))

module.exports = {
  // https://github.com/webpack/changelog-v5/blob/master/README.md#persistent-caching
  cache: {
    type: 'filesystem'
  },
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, '/dist'),
    // filename: 'bundle.js'
    filename: 'bundle-[contenthash].js'
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    modules: nodePathParts
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  },
  plugins: [new HtmlWebpackPlugin()]
}
``

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
  <div id="root"></div>
  <!-- <script type="text/javascript" src="bundle.js"></script> -->
</body>

</html>
```

## Relevant Links

[https://github.com/fengyun2/webpack5-demo](https://github.com/fengyun2/webpack5-demo)

## Additional context

```
D:\webpack5-demo\node_modules\html-webpack-plugin\index.js:142
          compilation.compilationDependencies.add(fileDependency);
                                              ^

TypeError: Cannot read property 'add' of undefined
    at childCompilerDependencies.forEach.fileDependency (D:\test\js\20190214\webpack5-demo\node_modules\html-webpack-plugin\index.js:142:47)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalChunkAssets.tap (D:\test\js\20190214\webpack5-demo\node_modules\html-webpack-plugin\index.js:141:35)
    at SyncHook.eval [as call] (eval at create (D:\test\js\20190214\webpack5-demo\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (D:\test\js\20190214\webpack5-demo\node_modules\tapable\lib\Hook.js:154:20)
    at cont (D:\test\js\20190214\webpack5-demo\node_modules\webpack\lib\Compilation.js:1316:38)
    at createChunkAssets.err (D:\test\js\20190214\webpack5-demo\node_modules\webpack\lib\Compilation.js:1352:6)
    at D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2825:7
    at done (D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2861:11)
    at D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2813:7
```

**Comment by jantimon** [comment] 2019-02-17 09:53
I guess that's a duplicate of https://github.com/jantimon/html-webpack-plugin/issues/1129

**Closed by jantimon** 2019-02-17 09:53 UTC

**Comment by evictor** [comment] 2019-03-06 21:36
@jantimon I don't think that this is a duplicate. For this particular issue (which I also have) this is 

I don't know if you are aware of this but I noted this section in the Webpack 5 changelog that is relevant to this issue:

> Removed compilationParams.compilationDependencies (since alpha.5)
> Plugins can add dependencies to the compilation by adding to compilation.file/context/missingDependencies

Note particularly that the breaking change causing this issue was introduced in Webpack 5 alpha.5; I can confirm this issues goes away when using Webpack 5 alpha.4
