### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by diegohaz** [jantimon/html-webpack-plugin#683] opened 2017-05-23 07:01 UTC
Not sure if that's a webpack regression or html-webpack-plugin bug, but with the latest version of webpack (v2.6), it started to throw that error.

Stack trace: https://travis-ci.org/diegohaz/arc/builds/234991673#L427

**Comment by diegohaz** [comment] 2017-05-23 07:29
Removing `node_modules/html-webpack-plugin/node_modules/webpack` folder fixed the issue.

Tried to fork this repo to see if I could fix it, but I couldn't even get tests to pass on a fresh install (even following instructions on https://github.com/jantimon/html-webpack-plugin#contribution).

**Comment by mastilver** [comment] 2017-05-24 13:26
> I couldn't even get tests to pass on a fresh install

I just rerun test on CI, everything is fine...

**Comment by mastilver** [comment] 2017-05-24 13:36
Upgrading to webpack@2.6 didn't cause any issue on one of my project

From what I can see, it looks like you have several version of webpack installed, can you run that for me and give me the output:
```
yarn
yarn ls webpack
```

**Comment by ocassio** [comment] 2017-05-24 15:16
In my case, there are several webpack versions indeed.
The reason is favicons-webpack-plugin package.
Not sure, why they didn't set webpack as peer dependency.

```
yarn list v0.24.5
├─ favicons-webpack-plugin@0.0.7
│  └─ webpack@1.15.0
└─ webpack@2.6.0
```

**Comment by diegohaz** [comment] 2017-05-24 15:41
![image](https://cloud.githubusercontent.com/assets/3068563/26412168/3bb5fe72-407e-11e7-87f8-0edad9032180.png)

**Comment by diegohaz** [comment] 2017-05-24 15:45
Running webpack build causes this error:
![image](https://cloud.githubusercontent.com/assets/3068563/26412260/8399732c-407e-11e7-81b0-1943e4ba0c38.png)

If I remove `node_modules/html-webpack-plugin/node_modules/webpack`, everything works.

It can be reproduced by cloning my repo https://github.com/diegohaz/arc, upgrading webpack to v2.6  (`yarn upgrade webpack`)  and running `yarn build`.

**Comment by mastilver** [comment] 2017-05-24 16:09
Can you run:
```
yarn install
yarn ls webpack
```

**Comment by mastilver** [comment] 2017-05-24 16:10
@ocassio Do you mind making a PR on: favicons-webpack-plugin

**Comment by diegohaz** [comment] 2017-05-24 16:33
@mastilver `yarn list webpack` only shows production dependencies. `yarn install` also install development dependencies, which includes https://github.com/jantimon/html-webpack-plugin/blob/master/package.json#L54

**Comment by mastilver** [comment] 2017-05-24 16:38
What I was trying to do with `yarn install` is to dedupe packages

I'm not really an expert with `yarn` so I believe you ;)

I will have a look at your repo tonight if I have some time

**Comment by diegohaz** [comment] 2017-05-24 16:40
It could be something related to yarn. Don't know. I'm really confused.

**Comment by mastilver** [comment] 2017-05-24 16:41
I believe it is but I wouldn't bet on it ;)

**Comment by diegohaz** [comment] 2017-05-24 16:50
Removing `node_modules` and `yarn.lock` and running `yarn` again fixed the issue. A lot of diff on `yarn.lock` though. Not sure what happened, but the issue can be closed for me.

**Comment by ocassio** [comment] 2017-05-24 17:03
@mastilver Seems like there is one already, but it's kinda stuck:
https://github.com/jantimon/favicons-webpack-plugin/pull/48

**Comment by mastilver** [comment] 2017-05-24 17:08
@diegohaz Great news! :)

I'm closing it down then

For future reference: this issue is caused by multiple version of `webpack` being installed
Make sure you only have one instance by running `npm ls webpack`:
- if you are using `yarn` follow this: https://github.com/jantimon/html-webpack-plugin/issues/683#issuecomment-303784280
- if it's coming from another package, make sure `webpack` is a `peerDependency` and not a `dependency` of that package
If neither of those, try running `npm dedupe` or deleting `node_modules` folder

**Closed by mastilver** 2017-05-24 17:08 UTC
