### ISSUE TITLE
Two entry points with different bundles 

### ISSUE THREAD

**Issue by palaniichukdmytro** [jantimon/html-webpack-plugin#977] opened 2018-06-13 09:03 UTC
## Expected behaviour

I use `webpack 4` and I have two entry points and use `HtmlWebpackPlugin` to inject bundle files using `<%=htmlWebpackPlugin.files.webpackManifest%>` in html.

Expected to bundle and insert for `loginPage` only login.js and vendor js, and for main page insert `main.js and vendors.js` bundles

## Current behaviour

When I use `chunks:['login']` I receive in html only one bundle file without vendor, if I do not I receive bundles for `main` entry point inside `loginPage` entry point.
![screenshot_4](https://user-images.githubusercontent.com/14881178/41340502-33747520-6f00-11e8-9205-6b20f32bc470.png)

## Environment
```
node - v9.5.0
npm - v5.6.0
"html-webpack-plugin": "^3.2.0",
"webpack": "^4.12.0",
win32 
```

### Config
```
const extractTextPlugin = require('extract-text-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CleanWebpackPlugin = require('clean-webpack-plugin')

const path = require('path')

// initialize version.js
require('child_process').exec('node ' + path.resolve('./../scripts/setAppVersion.js'), {cwd: '../'}, function (err, stdout, stderr) {
    console.log(err)
})

module.exports = {
    mode: 'development',
    devtool: 'source-map',
    entry: {
        main: './src/main.js',
        login: './src/components/loginPage/loginPage.js',
    },
    output: {
        filename: '[name].[chunkhash].js',
        path: path.resolve(__dirname, '../dist'),
        publicPath: '/',
    },
    plugins: [
        new CleanWebpackPlugin(['dist'], {
            root: path.join(__dirname, '..'),
        }),
        new extractTextPlugin({
            filename: 'bundle.css',
            disable: false,
            allChunks: true,
        }),
        new HtmlWebpackPlugin({
            template: './src/index.ejs',
            hash: true,
            inject: false,
            chunks: ['main'],
        }),
        // generate Login Page
        new HtmlWebpackPlugin({
            inject: false,
            template: './src/components/loginPage/index.ejs',
            hash: true,
            chunks: ['login'],
            filename: 'loginPage.html',
        }),
    ],
    module: {
        rules:[
            {
                test: /\.js$/,
                use: 'eslint-loader?{fix:true}',
                exclude: /node_modules/,
                enforce: 'pre',
            },
            {
                test: /\.html$/,
                exclude: /node_modules/,
                use: 'file-loader?name=[name].[ext]',
            },
            {
                test: /\.css$/,
                loader: 'style-loader!css-loader',
            },
            {
                test: /\.scss$/,
                use: extractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader!sass-loader',
                }),
            },
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader',
            },
            {
                test: /\.(eot|svg|ttf|woff|woff2)$/,
                loader: 'file-loader?name=fonts/[name].[ext]',
            },
            {
                test: /\.(png|mp4)$/,
                use: 'file-loader',
            },
        ],
    },
    performance: {hints: false},
    optimization: {splitChunks:{chunks: 'all'}},
}

```
```
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Login Page</title>
</head>
<body>
	<div id="loginPage"></div>
	<script id='modelJson' type='application/json'>
        {model}
    </script>
	<%=htmlWebpackPlugin.files.webpackChunkManifest%>
		<!-- <%=htmlWebpackPlugin.files.webpackManifest%> -->
</body>
</html>
```

**Comment by jantimon** [comment] 2018-06-13 09:58
Right now the feature you are talking about is not available.
We would have to find out:

If webpack adds 0.js as an entry module or as an child of datalocation.js
At which time during the build process the information about the relation between datalocation.js and 0.js is known
Could you please take a look at that?

(Duplicate of #968.)

**Closed by jantimon** 2018-06-13 09:58 UTC
