### ISSUE TITLE
TypeError: Cannot read property 'request' of undefined every time upgrade occurs (don't close please)

### ISSUE THREAD

**Issue by damianobarbati** [jantimon/html-webpack-plugin#757] opened 2017-08-08 11:51 UTC
`TypeError: Cannot read property 'request' of undefined` occurs every time `webpack` is upgraded and it's very bothersome.
The following was closed https://github.com/jantimon/html-webpack-plugin/issues/683 and the solution is correct: removing `node_modules` and reinstall everything again because of conflicts.

Now here an example where the error is fired (just upgraded webpack): how can I identify the troublesome modules to ask maintainer to update their dependencies?

```
imac:react-app damz$ npm ls webpack
react-app@1.0.17 /Users/damz/Desktop/react-app
├─┬ favicons-webpack-plugin@0.0.7
│ └── webpack@1.15.0 
├─┬ html-webpack-plugin@2.30.1
│ └── webpack@1.15.0  extraneous
├─┬ react-create-app@1.0.9
│ └── webpack@3.5.1  deduped
├─┬ react-create-store@1.0.10
│ └── webpack@3.5.1  deduped
├─┬ string-replace-loader@1.3.0
│ └── webpack@1.15.0  extraneous
├─┬ stylelint-webpack-plugin@0.9.0
│ └── webpack@1.15.0  extraneous
└─┬ webpack@3.5.1 
  └─┬ uglifyjs-webpack-plugin@0.4.6
    └── webpack@1.15.0  extraneous
```

**Comment by mastilver** [comment] 2017-08-08 11:58
@damianobarbati How do you install your dependencies?

It looks like npm or yarn is including devDependencies which is wrong

**Comment by damianobarbati** [comment] 2017-08-08 12:00
Really? I just run `yarn install`.
Here the pkg: https://github.com/damianobarbati/react-app/blob/master/package.json

**Comment by mastilver** [comment] 2017-08-08 12:20
I couldn't reproduce it...

- `git checkout v1.0.17`
- `yarn`
- `yarn build:prod`
- `git pull`
- `yarn`
- `yarn build:prod`

**Comment by mastilver** [comment] 2017-08-08 12:21
```
$ yarn --version 
0.20.3
```

**Comment by damianobarbati** [comment] 2017-08-08 12:23
@mastilver you can only reproduce it:
1. downgrading webpack (so in package.json will be the previous version)
2. remove yarn.lock and node_modules and install
3. yarn upgrade-interactive => upgrade everything
4. error is fired

```
imac:react-app damz$ yarn --version
0.24.6
imac:react-app damz$ node -v
v8.2.1
```

**Comment by mastilver** [comment] 2017-08-08 12:37
No, I'm sorry still working fine for me...

**Comment by damianobarbati** [comment] 2017-08-08 12:41
I just reproduced with the following :(((
```
  511  yarn add webpack@3.5.0
  512  rm -rf node_modules/ yarn.lock 
  513  yarn install
  514  yarn upgrade-interactive
  515  yarn build:dev
```

**Comment by mastilver** [comment] 2017-08-08 12:47
Followed what you wrote, no problem for me

Try a new version of yarn

**Comment by damianobarbati** [comment] 2017-08-08 13:03
@mastilver same error with `0.27.5` (thanks for the hint anyway, I had to install it with brew instead of npm -g).

What version of yarn are you using?

**Comment by mastilver** [comment] 2017-08-08 13:28
Using 0.27.5 no issue

**Comment by jantimon** [comment] 2017-08-08 13:40
Can you please run `npm ls` and post the result?

**Comment by damianobarbati** [comment] 2017-08-08 13:54
Sure, this is before upgrading and without errors =>  https://pastebin.com/raw/Fsvw1ywJ
Here after upgrading and with error => https://pastebin.com/raw/a22XkudN

**Comment by mastilver** [comment] 2017-08-08 13:57
> Sure, this is before upgrading and without errors => https://pastebin.com/raw/Fsvw1ywJ
> Here after upgrading and with error => https://pastebin.com/raw/a22XkudN

The diff: https://www.diffchecker.com/BHVZT1CJ

**Comment by mastilver** [comment] 2017-08-08 14:02
I don't get why `webpack` is added under `stylelint-webpack-plugin` when it's only a peerDependency: https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/package.json#L34

**Comment by jantimon** [comment] 2018-03-01 06:16
Will close this for now as spring cleanup - please reopen if you still need support here

**Closed by jantimon** 2018-03-01 06:16 UTC
