### ISSUE TITLE
After compiling with webpack, an extra strange file is generated."javascript,__webpack_public_path__ __webpack_base_uri__ htmlWebpackPluginPublicPath;.1feff74faaf0efc6a044355c92cd15d9.bin"

### ISSUE THREAD

**Issue by masx200** [jantimon/html-webpack-plugin#1646] opened 2021-05-21 01:27 UTC
After compiling with webpack, an extra strange file is generated."javascript,__webpack_public_path__ __webpack_base_uri__ htmlWebpackPluginPublicPath;.1feff74faaf0efc6a044355c92cd15d9.bin"

https://github.com/jantimon/html-webpack-plugin/blob/0a6568d587a82d88fd3a0617234ca98d26a1e0a6/lib/child-compiler.js#L119

https://github.com/masx200/webpack-react-vue-spa-awesome-config/blob/e57aae232916ab10335633ce99d862e9c8bdead0/release/config/webpack.config.js#L439

`javascript,__webpack_public_path__ __webpack_base_uri__ htmlWebpackPluginPublicPath;.1feff74faaf0efc6a044355c92cd15d9.bin`

`__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;`

"webpack": "^5.37.1",

"webpack-cli": "^4.7.0",

 "html-webpack-plugin": "^5.3.1",

nodejs  v16.1.0

**Comment by masx200** [comment] 2021-05-21 01:36
<code>


"/node12/bin/node",
"/vercel/path0/node_modules/@masx200/webpack-react-vue-spa-awesome-config/node_modules/.bin/webpack",
"--config",
 "/vercel/path0/node_modules/@masx200/webpack-react-vue-spa-awesome-config/release/config/webpack.config.js",
"--mode=production"




07:13:44.688 | assets by path *.js 725 KiB
-- | --
07:13:44.689 | assets by info 701 KiB [immutable]
07:13:44.690 | assets by chunk 426 KiB (id hint: vendors) 13 assets
07:13:44.690 | 20 assets
07:13:44.690 | asset workbox-f2271462.js 19.6 KiB [emitted] [minimized]
07:13:44.690 | asset service-worker.js 4.27 KiB [emitted] [minimized]
07:13:44.691 | asset parcel.164cd91c583b612c6a3314f4dee5152b.jpg 21.9 KiB [emitted] [immutable] [from: src/pictures/parcel.jpg]
07:13:44.691 | asset main.dbfb55859b57951aafd9.css 17.2 KiB [emitted] [immutable] (name: main)
07:13:44.691 | asset babeljs.93957982db09411054d96cee5af63acc.png 12.1 KiB [emitted] [immutable] [from: src/pictures/babeljs.png]
07:13:44.691 | asset favicon.ico 3.78 KiB [emitted] [from: public/favicon.ico] [copied]
07:13:44.692 | asset index.html 889 bytes [emitted]
07:13:44.692 | asset javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;.1feff74faaf0efc6a044355c92cd15d9.bin 77 bytes [emitted] [immutable] [from: data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;]
07:13:44.692 | asset service-worker-jsfuck.worker.5ecbfb31bebf00e618d5.worker.js.LICENSE.txt 40 bytes [emitted]
07:13:44.692 | Entrypoint main 149 KiB = bundle.runtime.04658f27b82e6ae00384.js 4.38 KiB bundle.2.5a7883349955b79da119.js 11.4 KiB bundle.3.83a1e32a350376ed8625.js 115 KiB main.dbfb55859b57951aafd9.css 17.2 KiB bundle.main.dbfb55859b57951aafd9.js 1.07 KiB
07:13:44.692 | orphan modules 254 KiB [orphan] 80 modules
07:13:44.693 | runtime modules 9.62 KiB 15 modules
07:13:44.693 | cacheable modules 1.19 MiB
07:13:44.693 | modules by path ./node_modules/ 976 KiB 96 modules
07:13:44.693 | modules by path ./src/ 242 KiB 18 modules
07:13:44.694 | ./util.inspect (ignored) 15 bytes [built] [code generated]
07:13:44.694 | css modules 21.5 KiB
07:13:44.694 | modules by path ./src/assetscss/ 13.2 KiB 5 modules
07:13:44.694 | modules by path ./src/*.css 8.28 KiB 3 modules
07:13:44.695 | modules by path ./src/components/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/*.tsx + 1 modules 23.5 KiB
07:13:44.695 | ./src/components/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/react-module-jsfuck.tsx + 1 modules 12.4 KiB [not cacheable] [built] [code generated]
07:13:44.695 | ./src/components/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/react-module-hieroglyphy.tsx + 1 modules 11.2 KiB [not cacheable] [built] [code generated]
07:13:44.695 | ./src/components/home-react-module-picalc.js + 4 modules 91 KiB [not cacheable] [built] [code generated]
07:13:44.696 | LOG from GenerateSW
07:13:44.696 | &lt;i&gt; The service worker at service-worker.js will precache
07:13:44.696 | &lt;i&gt;         47 URLs, totaling 777 kB.
07:13:44.698 | webpack 5.37.1 compiled successfully in 17032 ms
07:13:44.754 | child process exited with code 0





<code/>

**Comment by jantimon** [comment] 2021-05-27 07:05
duplicate of https://github.com/jantimon/html-webpack-plugin/issues/1589#issuecomment-830845614

**Closed by jantimon** 2021-05-27 07:05 UTC
