### ISSUE TITLE
How to make html files output to a different directory

### ISSUE THREAD

**Issue by huangshuwei** [jantimon/html-webpack-plugin#665] opened 2017-05-09 03:10 UTC
now I want html files to output to different directories，because my project contains a single page application entry and multiple pages entry.the entry option such as:
```
var entry = {
    index: './app/index.js',
    test1:'./pages/js/test1.js',
    test2:'./pages/js/test2.js',
    vendors: [
        'babel-polyfill',
        'vue',
        'vue-router',
        'vuex'
    ]
};
```

I wish my file output directory is:
```
├─css
│
├─js
│
└─pages (multiple pages)
 │      test1.html
 │       test2.html
 │
 │  index.html  (single page application entry)

```

and I have already used the publicPath option:
```
publicPath:'./'
```

also I used html-webpack-plugin:

```
  new HtmlWebpackPlugin({
        filename: './index.html',
        template: __dirname + '/app/index.html',
        inject: 'true',
        chunks: ['index', 'vendors', 'webpackAssets'],
        chunksSortMode: 'dependency'
    }),
    new HtmlWebpackPlugin({
        filename: './pages/test1.html',
        template: __dirname + '/pages/test1.html',
        inject: 'true',
        chunks: ['test1', 'vendors', 'webpackAssets'],
        chunksSortMode: 'dependency'
    }),
    new HtmlWebpackPlugin({
        filename: './pages/test2.html',
        template: __dirname + '/pages/test2.html',
        inject: 'true',
        chunks: ['test2', 'vendors', 'webpackAssets'],
        chunksSortMode: 'dependency'
    })
```

When I output the file via webpack, only the single page application entry file(index.html) correctly references css and js. Multi-page file css and js path is wrong.

So what should I do？

**Comment by mastilver** [comment] 2017-05-09 08:36
The ```publicPath:'./'``` is weird

Can you try ```publicPath:'/'``` instead

**Comment by mastilver** [comment] 2017-05-09 08:42
Can you also give the the "good" paths and "wrong" paths

**Comment by mastilver** [comment] 2017-05-11 14:15
Closing this as I assume, the above answer solved your issue

Feel free to reach back if it didn't!

**Closed by mastilver** 2017-05-11 14:15 UTC

**Comment by huangshuwei** [comment] 2017-05-17 02:26
@mastilver 
I have already used the publicPath option:

```
publicPath:'./'
```
The problem is when I use the publicPath attribute, multiple pages can not correctly reference js, css and other resources.

This is the output file directory:
![2017-05-17_101643](https://cloud.githubusercontent.com/assets/6047141/26135781/716ff430-3aea-11e7-816c-50123ac5e003.png)

but multiple pages can not correctly reference js, css and other resources.
 such as test1.html, Inline resource reference is:
![1](https://cloud.githubusercontent.com/assets/6047141/26135876/0a8b3a6c-3aeb-11e7-9baf-5445192119d7.png)

and the resource reference for a single page application is correct.

**Comment by mastilver** [comment] 2017-05-17 08:43
As I said earlier, please use `publicPath:'/'` **without** the dot

**Comment by lkiarest** [comment] 2017-05-20 03:03
@mastilver if we use '/' as publicPath, it'll be another problem: the context path will be ignored while the  http server hosts our files within a context path like 'http://ip:port/context-path/test1.html'.  it's better if we can set **relative path** for js/css references

**Comment by lkiarest** [comment] 2017-05-20 07:56
@huangshuwei  I have write a plugin to correct the relative path [html-webpack-plugin-assets-fix](https://github.com/lkiarest/html-webpack-plugin-assets-fix), hope it'll help

**Comment by mastilver** [comment] 2017-05-20 09:04
@lkiarest If you want to keep the page context, then just use: `publicPath:''`

**Comment by lkiarest** [comment] 2017-05-22 01:08
hi @mastilver, thanks for you suggestion, bu if we set publicPath as '', the html has same problom as huangshuwei posted: 
`
but multiple pages can not correctly reference js, css and other resources.
such as test1.html
`

**Comment by huangshuwei** [comment] 2017-05-22 01:32
@mastilver 
This question bothers me for a long time，I can only output multiple pages and single pages to the same directory. And I hope html-webpack-plugin can support relative directory output , such as :
```
new HtmlWebpackPlugin({
        filename: './pages/test1.html',
        template: __dirname + '/pages/test1.html',
        chunks: ['test1'],
        path:'../'
    })
```

**Comment by huangshuwei** [comment] 2017-05-22 01:45
@lkiarest 

> @huangshuwei I have write a plugin to correct the relative path html-webpack-plugin-assets-fix, hope it'll help

thanks for your help, I'll try it.

**Comment by mastilver** [comment] 2017-05-22 15:52
@huangshuwei you can do `filename: 'pages/test1.html'` for that

https://github.com/jantimon/html-webpack-plugin#configuration

**Comment by huangshuwei** [comment] 2017-05-23 01:36
> @huangshuwei you can do filename: 'pages/test1.html' for that
>https://github.com/jantimon/html-webpack-plugin#configuration

But the multi-page resource reference address has not changed

**Comment by mastilver** [comment] 2017-05-23 17:08
We are not going anywhere with that issue, just create a repository with your issue and I will solve it for you...

**Comment by raRaRa** [comment] 2017-07-05 11:21
@huangshuwei Did you ever find a solution? I'm running into the same issue.

Goal: Have sub-folders with index.html that can reference the assets using relative path.
Reason: On S3 I want to have multiple websites in one bucket. /website1/, /website2/, etc. I also have sub-pages such as /website1/test/ where test has its own template file. That way I can set meta tags and stuff customized for that page, since the app is static.

**Comment by mastilver** [comment] 2017-07-05 21:09
@raRaRa if you can give us a repository, I will have a look at your issue

**Comment by chrisalexander55** [comment] 2017-09-01 23:34
I am revisiting webpack after 2 years and having the same issue; clearly this issue has not been resolved. I have set-up a repo to boilerplate my own webpack work that generates the same dist/ structures as @huangshuwei and subdirectory HTML pages don't inject bundles/chunks correctly while the root context index.html page does. The repo is here [ecmascript-sass-webpack-starter](https://github.com/chrisalexander55/ecmascript-sass-webpack-starter). Any help would be appreciated.

I also opened my own issue that matches,  [Webpack Dev Configuration Does Not Inject Bundles into Sub-directory HTML Pages](https://github.com/chrisalexander55/ecmascript-sass-webpack-starter/issues/2)

**Comment by mastilver** [comment] 2017-09-02 15:09
@chrisalexander55 As I said earlier, use `publicPath:'/'`

**Comment by chrisalexander55** [comment] 2017-09-02 16:34
It is already there: [publicPath: '/'](https://github.com/chrisalexander55/ecmascript-sass-webpack-starter/blob/master/webpack/dev.config.js#L26).

So let me state that I have no issues when transpiling my production bundles, things are just fine. However, when using html-webpack-plugin with webpack-dev-server (with or without the HotModuleReplacementPlugin) only index.html has inject bundles. HTML docs in pages/ have nothing injected. So, is this a html-webpack-plugin or webpack-dev-server config issue even though I am using publicPath: '/' per this thread's guidance?

**Comment by chrisalexander55** [comment] 2017-09-02 20:15
@huangshuwei @raRaRa  Did you ever find a workaround for this potential defect? I have it working for production builds but not dev iterative development using webpack-dev-server. Thanks!

**Comment by mastilver** [comment] 2017-09-03 00:46
@chrisalexander55 I had a lot of trouble getting around your project.

But I added `publicPath` to prod config and got it working

Please give me a way to replicate your issue

**Comment by chrisalexander55** [comment] 2017-09-03 03:33
@mastilver Thank you for taking the time - it is appreciated.

So I cleaned up my package.json and added publicPath: '/' to the output attribute of prod.config.js. Still no difference. Here are the gists of the output:

* sub-directory document [pages/some-page-1.html](https://gist.github.com/chrisalexander55/c19dbf4691c98a4de2e2e9eda31c3143) has correct script paths
* root document [index.html](https://gist.github.com/chrisalexander55/8fe65b086321541fbaf3d40b11e01134) has incorrect and correct script paths

Obviously, the goal is to have index.html and sub-directory html files injected with the correct paths. Is there a prod mis-configuration I am making here or should I include another plugin in the processing chain? I am assuming once this is resolved, I can tackle testing with webpack-dev-server. Thanks.

**Comment by mastilver** [comment] 2017-09-03 09:37
@chrisalexander55 I'm sorry, I still couldn't reproduce it...

There is something weird that I don't understand in your index template, why do you already have scripts tag in there?

**Comment by chrisalexander55** [comment] 2017-09-04 15:03
@mastilver 

I removed the excessive starter/boilerplate commenting I had in my <header> region and all is working as expected: correct relative paths. So you are correct. Moving forward I wonder if this may possibly be revisited once a static <header> is coded and the document undergoes continual editing/transpilation. If I see any weird stuff, I'll post my observations with working use case.

Thanks for your help! All the best.

**Comment by tsuijie** [comment] 2018-04-30 09:12
If you need to output html to a separate directory, in my case outside the ```dist``` directory, you can do ```filename: '../index.html'``` for that. Absolute path also works: ```filename: path.resolve(__dirname, '/some/directory/index.html')```
Pretty tricky.

**Comment by jantimon** [comment] 2018-04-30 15:45
@tsuijie this will cause issues with your webpack dev server - my recommendation is to generate the js file into a sub directory: `output: { filename: { 'js/[name].js' } }`
