### ISSUE TITLE
The webpack prefetch does not take effect

### ISSUE THREAD

**Issue by chnliquan** [jantimon/html-webpack-plugin#1188] opened 2019-04-01 07:59 UTC
## Expected behaviour
The html should have a <link rel="preload" /> tag

## Current behaviour
I use webpack prefetch like this:

```js
document.addEventListener('click', () => {
  // https://webpack.js.org/guides/code-splitting#prefetchingpreloading-modules
  import(/* webpackPrefetch: true */ './click').then(({ default: func, }) => {
    func()
  })
})
```
the bundle includes these files 

```
index.html
2.9d82f42d43a50d59b4e4.js (split chunk above)
0.index.css
...
```
the html content as follow, it does not have a <link rel="preload" /> tag

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Webpack</title>
  <link href="0.index.css" rel="stylesheet">
</head>

<body>
  <div id="root"></div>
  <script src="vendors.dll.js"></script>
  <script src="react.dll.js"></script>
  <script src="manifest.9db9f263eaea975b6d53.js"></script>
  <script src="main.ccffa7111bf5b3411965.js"></script>
</body>

</html>
```

## Environment
node: 8.12.0
webpack: 4.29.0
html-webpack-plugin: 4.0.0-beta.5
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Additional context

Add any other context about the problem here.

**Comment by jantimon** [comment] 2019-04-01 11:54
Most people are using the `webpack-dev-server` during development and therefore don't need to add the `index.js` file manually.

Therefore this plugin will never delete scripts from the html file as it does not know which to delete and which to keep.

However you might just have two templates - one for development and one for production to workaround this issue.

**Comment by jantimon** [comment] 2019-04-01 11:55
Yes that's true - that is a duplicate of issue #1150.

**Closed by jantimon** 2019-04-01 11:55 UTC
