### ISSUE TITLE
Conflict: Multiple assets emit to the same filename index.html

### ISSUE THREAD

**Issue by mistic** [jantimon/html-webpack-plugin#599] opened 2017-02-23 17:17 UTC
Hey guys,

Are you having problems in using html webpack plugin with webpack.optimize.AggressiveSplittingPlugin ? 

Using the 2 plugins at the same time I'm having this error:

`ERROR in   Error: Child compilation failed:
  Conflict: Multiple assets emit to the same filename index.html:
  Error: Conflict: Multiple assets emit to the same filename index.html`

Thanks in advance

**Comment by bruno-serfe** [comment] 2017-03-14 18:00
Same issue here.

**Comment by jamessharp** [comment] 2017-04-21 13:34
I have a fix that is doing the job for me here: https://github.com/ortoo/html-webpack-plugin/commit/6d9996d8bd143d5026d63c78d91cd8d0c920c058 (see my comment [here](https://github.com/jantimon/html-webpack-plugin/issues/446#issuecomment-293894911) for more details)

**Comment by mastilver** [comment] 2017-05-20 09:36
Closing as a duplicate of #446

**Closed by mastilver** 2017-05-20 09:36 UTC
