### ISSUE TITLE
Build order for HtmlWebpackPlugin module?

### ISSUE THREAD

**Issue by danchristian** [jantimon/html-webpack-plugin#718] opened 2017-06-23 16:15 UTC
## Description

The `/dist` folder is in `.gitignore` so therefore empty,  the build is then failing in production as `CopyWebpackPlugin` is looking in `/dist` for files to copy elsewhere but it errors with: 

```
ERROR in [copy-webpack-plugin] unable to locate '/dist/app.html'
```

I would expect `HtmlWebpackPlugin` to build these files first before the `CopyWebpackPlugin` starts to look for them? 

### Config
```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

new HtmlWebpackPlugin({
    title: 'App',
    filename: 'app.html',
    template: './src/app.pug',
    inject: 'head',
    chunks: ['app'],
    hash: true
}),

new CopyWebpackPlugin([
    {from: 'dist/app.html',   to: '../Views/Shared/_layout.cshtml'}
])
```
## Environment
```
Node.js v6.9.4
darwin 16.6.0
npm --version (3.10.10)
npm ls webpack (2.6.1)
npm ls html-webpack-plugin (2.28.0)
```

**Comment by mastilver** [comment] 2017-06-23 16:44
> I would expect HtmlWebpackPlugin to build these files first before the CopyWebpackPlugin starts to look for them?

yes you are right, I believe the issue is that `copy-webpack-plugin` is using `emit` instead of `after-compile`: https://github.com/kevlened/copy-webpack-plugin/blob/master/src/index.js#L49

Do you mind reaching out to that project, to see if that's the way to solve it? Or even better open a PR! ;)

NOTE: It's the first time I'm looking at their code, so I'm just making assumption, I could be completely wrong here

**Comment by mastilver** [comment] 2017-11-15 12:23
closing this as it should be handled by `copy-webpack-plugin`

**Closed by mastilver** 2017-11-15 12:23 UTC

**Comment by danchristian** [comment] 2017-11-15 12:27
I did actually reach out to the `copy-webpack-plugin` project. Sorry I forgot to update this ticket. I will leave the link to the issue for reference:

https://github.com/webpack-contrib/copy-webpack-plugin/issues/133

**Comment by mastilver** [comment] 2017-11-15 12:50
yeah, I noticed ;)

Thank you for doing it BTW
