### ISSUE TITLE
”Cannot read property 'tap' of undefined“ in version 4.5.1

### ISSUE THREAD

**Issue by Lynn-cc** [jantimon/html-webpack-plugin#1593] opened 2021-02-03 11:27 UTC
## Current behaviour 💣

I force update html-webpack-plugin to 4.5.1 in @vue/cli-server and this error occurs:
ERROR  TypeError: Cannot read property 'tap' of undefined
It may because vue-cli use the webpack-chain API:https://github.com/Yatoo2018/webpack-chain
But version 3.2.0 works right.

## Expected behaviour ☀️
No errors.

**Comment by jantimon** [comment] 2021-02-03 11:44
Is that a duplicate of https://github.com/jantimon/html-webpack-plugin/issues/1377 ?

**Comment by jantimon** [comment] 2021-02-05 09:26
It's an issue with vue-cli: https://github.com/vuejs/vue-cli/issues/6109

**Closed** 2021-02-05 09:26 UTC
