### ISSUE TITLE
'chunksSortMode' has no effect

### ISSUE THREAD

**Issue by chrisckc** [jantimon/html-webpack-plugin#1115] opened 2018-11-28 15:41 UTC
'chunksSortMode' has no effect

The documentation states:

> Allows to control how chunks should be sorted before they are included to the HTML. Allowed values are 'none' | 'auto' | 'dependency' | 'manual' | {Function}

However in the source code, 'auto' is set to 'none' which does no sorting.

'dependency' is not implemented.

'manual' is not actually a sort mode, it just filters chunks using the array supplied in the 'chunks' property

Relevant source:
https://github.com/jantimon/html-webpack-plugin/blob/master/lib/chunksorter.js

and also:
https://github.com/jantimon/html-webpack-plugin/blob/7095cd66bdb6b68c00abf521dcf11d4547cb9475/index.js#L479-L489

This behaviour is also mentioned in this closed issue from a while back:
https://github.com/jantimon/html-webpack-plugin/issues/481

## Expected behaviour

The documentation should match the behaviour of the source code.

## Current behaviour

Either the documentation or the source is incorrect?

## Comments:

It seems that the only way to sort chunks is by using a sort function on chunksSortMode

Question: Does the order of the chunks in index.html actually matter?  Is the JS only executed by the webpack runtime once all of the chunks are downloaded?

Or does it only matter that the entry chunk is first in the index.html?

When using  'optimization.runtimeChunk: true', the runtime chunk becomes the entry chunk, i have tried making this first and last in the index.html and it makes no difference, the app works fine both ways. I have tried changing the order of other chunks and have so far been unable to break it.

**Comment by jantimon** [comment] 2018-11-28 16:01
In webpack 4 that was changed - so the order is not important anymore

**Comment by tenjojeremy** [comment] 2019-04-24 23:42
@jantimon Using webpack 4, does setting `chunksSortMode: 'none'` have any negative effects?

**Comment by rakcheru** [comment] 2019-04-29 17:21
> @jantimon Using webpack 4, does setting `chunksSortMode: 'none'` have any negative effects?

@jantimon : looking for pointers on same. Thanks in advance

**Comment by jantimon** [comment] 2019-04-30 12:41
I moved that to a [stackoverflow question](https://stackoverflow.com/questions/55921186/does-the-script-tag-order-matter-for-webpack-generated-files)

**Comment by LaurensRietveld** [comment] 2019-07-19 06:59
I was confused by the sort mode as well. My use case was a webpack config with multiple entrypoints where some packages were externals that needed to be included in a particular order. I was expecting that the `manual` sortmode would help here. Instead (based on the op) I went with this workaround:
```
const chunks = ['a', 'b', 'c'];
const plugin = new HtmlWebpackPlugin({
    filename: "index.html",
    template: path.resolve(__dirname, "index.html"),
    chunks: chunks,
    chunksSortMode: (lhs, rhs) => chunks.indexOf(lhs.id) - chunks.indexOf(rhs.id)
  })
```

**Comment by jantimon** [comment] 2019-07-19 07:12
@LaurensRietveld try sortMode 'manual' it will use the same order as your `chunks` array

**Comment by LaurensRietveld** [comment] 2019-07-19 07:21
@jantimon You're right, I was fighting a different (unrelated) issue it seems. Apologies for the noise!

**Comment by glittle** [comment] 2019-09-30 22:03
The readme lists `dependency` as a possible value for `chunksSortMode`, but looking at lib/chunksorter.js shows that it is not valid.  The documentation should be fixed up.

**Comment by jahed** [comment] 2019-10-10 01:33
>Question: Does the order of the chunks in index.html actually matter?

Yes, it matters for CSS.

I came across this issue after I changed `optimization.chunkIds` to `named`. So my entry point `client.css` was injected before `vendors.css`. Since html-webpack-plugin doesn't support sorting by `dependency` as the docs say, CSS ordering is broken.

```
{
"entrypoints": {
    "client": {
      "chunks": [
        "runtime",
        "vendors",
        "client"
      ],
      "assets": [
        "js/runtime-86e22b4f3003b3926687.js",
        "js/runtime-86e22b4f3003b3926687.js.map",
        "css/vendors-608d6b30cfade68e50cd.css",
        "js/vendors-608d6b30cfade68e50cd.js",
        "js/vendors-608d6b30cfade68e50cd.js.map",
        "css/client-00cabc29dfe4afd77cc1.css",
        "js/client-00cabc29dfe4afd77cc1.js",
        "js/client-00cabc29dfe4afd77cc1.js.map"
      ],
      "children": {
      },
      "childAssets": {
      }
    }
  }
}
```

I've tried looking into the cause. The files under `stats.entrypoints["client"].assets` in my case are correctly ordered so I can only assume the way `html-webpack-plugin` retrieves the files is providing them unordered. Somewhere here maybe:

https://github.com/jantimon/html-webpack-plugin/blob/35a154186501fba3ecddb819b6f632556d37a58f/index.js#L601

I can't find documentation on `getFiles` so I'm guessing it's part of the many undocumented Webpack APIs.

Anyways, in this case, `chunksSortMode` would be useful, assuming `dependency` would fix this. Or if Webpack provides assets in the correct dependency order with a different API, that would remove the need for `chunksSortMode` or at least provide correct `auto` behaviour.

**Closed** 2020-03-24 09:41 UTC
