### ISSUE TITLE
Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by maidishike** [jantimon/html-webpack-plugin#672] opened 2017-05-15 02:05 UTC
this is my code:
  **compilation.assets[htmlWebpackPlugin.files.chunks.ioshacker.entry.substr(htmlWebpackPlugin.files.publicPath.length)].source()**

run webpack, an error occurred:
**ERROR in Template execution failed: TypeError: Cannot read property 'source' of undefined**

**Comment by mastilver** [comment] 2017-05-15 16:58
Not sure, what you are trying to do here...

Can you explain us your intention and  maybe we can help find you a way to do it

**Comment by maidishike** [comment] 2017-05-16 01:31
https://github.com/jantimon/html-webpack-plugin/blob/master/examples/inline/template.jade
I want to inject the specified JS code into the specified place，for example, the head or body.ioshacker is a chunk，I want to inject its source code into the head

**Comment by mastilver** [comment] 2017-05-16 09:02
I see...

Have you tried using: https://github.com/DustinJackson/html-webpack-inline-source-plugin

Overwise, can you give ur your index file and webpack.config.js

**Comment by mastilver** [comment] 2017-05-20 09:25
Closing this, as I didn't hear back from you

**Closed by mastilver** 2017-05-20 09:25 UTC

**Comment by abozhinov** [comment] 2017-07-16 19:40
I have same error.
ERROR in   TypeError: Cannot read property 'source' of undefined
The problem is when i set:
  filename: '../layout/index.html'

        new HtmlWebpackPlugin({
            inlineSource: '.(js|css)$',
            inject: 'head',
            excludeChunks: ['app'],
            template: './layout/index.html',
            filename: '../layout/index.html'
        }),
        new HtmlWebpackInlineSourcePlugin()

**Comment by mastilver** [comment] 2017-07-16 20:54
@abozhinov Have you tried using a more webpack friendly `filename`?  (Without using `../`)

What is the value of `output.path`? It looks like you are using the same `template` and `filename`

**Comment by chaishi** [comment] 2017-11-23 12:36
I have the same error. 

webpack.prod.config.js
```
const path = require('path')
const webpack = require('webpack')
const baseConfig = require('./webpack.base.config')

const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const OptimizeCSSPlugin = require('optimize-css-assets-webpack-plugin')
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')

module.exports = Object.assign(baseConfig, {
  entry: './example/main.js',
  output: {
    path: path.resolve(__dirname, '.'),
    filename: '../example/dist/index.js'
  },
  plugins: [
    new ExtractTextPlugin('../example/dist/index.css'),
    new HtmlWebpackPlugin({
      filename: '../example/dist/index.html',
      template: './example/index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
      },
      inlineSource: '.(js|css)$'
    }),
    new OptimizeCSSPlugin({
      cssProcessorOptions: {
        safe: true
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        drop_console: true,
        drop_debugger: true
      },
      output: {
        comments: false
      },
      sourceMap: true
    }),
    new HtmlWebpackInlineSourcePlugin()
  ]
})

```

but the follow config is ok. (webpack.dev.config.js)

```
const path = require('path')
const webpack = require('webpack')
const baseConfig = require('./webpack.base.config')

const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin')

module.exports = Object.assign(baseConfig, {

  devtool: '#cheap-module-eval-source-map',

  entry: [
    'webpack-hot-middleware/client',
    './example/main.js'
  ],

  output: {
    path: path.resolve(__dirname, '.'),
    filename: 'index.js',
    publicPath: '/'
  },

  plugins: [
    new ExtractTextPlugin('dist/index.css'),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './example/index.html',
      inject: true,
      inlineSource: '.(js|css)$'
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackInlineSourcePlugin()
  ]
})
```

I want to konw why the former is bad, throw Error as the #inssue title ?

Thanks so much for you answer.
