### ISSUE TITLE
Using Compression plugin alongside Html Webpack plugin

### ISSUE THREAD

**Issue by retwedt** [jantimon/html-webpack-plugin#678] opened 2017-05-16 16:45 UTC
Is it possible to make the Html Webpack plugin insert a link to the .gz build file instead of the normal .js build file?

Is this even the right place to ask this question??

Thanks for your help, and thanks for your work on a great plugin!

**Comment by mastilver** [comment] 2017-05-16 19:18
duplicate of #61

It's something that out of your control, you will need to wait for compression-webpack-plugin@1

**Closed by mastilver** 2017-05-16 19:18 UTC

**Comment by retwedt** [comment] 2017-05-16 19:21
Thanks!

**Comment by varenya** [comment] 2018-01-29 06:27
has there been a update on this?

**Comment by jantimon** [comment] 2018-04-19 07:47
The `compression-webpack-plugin` hooks into the `emit`phase to find files which should be compressed.

https://github.com/webpack-contrib/compression-webpack-plugin/blob/a389f2dbdda9f084487618d8e8b9e0c210515c33/src/index.js#L148-L154

While the `html-webpack-plugin` does the same to add the html file to webpack:

https://github.com/jantimon/html-webpack-plugin/blob/75eef8876bb54e80f9493a544759493ed385d7e0/index.js#L90

My guess it that you registered `compression-webpack-plugin` before the `html-webpack-plugin` so the html file is added after the compression is complete.

To prevent this behaviour we would have to adjust the `compression-webpack-plugin` as this can't be changed here.

**Comment by jantimon** [comment] 2018-04-21 07:35
Please make sure that the html-webpack-plugin is first in your plugins array - then it should work.  
If not open an issue for the compression webpack plugin :)

**Comment by noobG** [comment] 2018-04-23 14:12
@thegoldenmule 

Have same issue, but after looking further into it, I've concluded that this is actually a web server problem; you can't have a .gz source in your script tag src attribute; your web server should be configured to return the gzipped version of your bundle when receiving the request in production mode. 

Here is an example way to do it with nginx: http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by thegoldenmule** [comment] 2018-04-23 15:36
@jantimon I will try presently.

@noobG This is not a webserver problem. I already have Apache configured to serve with correct headers as I'm serving other assets that way. Regardless of what you name it (.js or .gz), in this case the plugin does not insert the output of the plugin before it. It presents as a bug. The point of an array is to order elements, and in this case you have to unorder them-- a bit of a screwy interface IMO.

**Comment by mastilver** [comment] 2018-04-23 15:48
If it's a plugin position issue, we can fix that by using the `stage` option on tap, see: https://github.com/danethurber/webpack-manifest-plugin/pull/142/files

**Comment by jantimon** [comment] 2018-04-23 16:00
@mastilver that's a cool idea

**Comment by thegoldenmule** [comment] 2018-04-23 23:15
I tried reordering them, but it had no effect.

**Comment by thegoldenmule** [comment] 2018-05-01 16:04
Hi there, I'm unclear on how to proceed. This cannot be an uncommon use case, right? Gzip build -> add script tag? What am I missing?

**Comment by noobG** [comment] 2018-05-01 21:11
@thegoldenmule I think the problem is that the webpack plugin pipeline is roughly just a series of functions that operate sequentially on the webpack output (correct me if I'm wrong); if this is the case, html-webpack-plugin can't (and shouldn't) assume arbitrary files added by prior plugins are meant to go in the script tag

Did some digging and found the actual place the script tags seem to be inserted, and it looks like the logic is simply to add a script tag for each js asset

https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L513
