### ISSUE TITLE
Webpack 5: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by ebuchmann** [jantimon/html-webpack-plugin#1451] opened 2020-05-29 21:36 UTC
## Expected behaviour

Should correctly update the html file with script tags.

## Current behaviour

Trying to update my project to webpack 5 beta 16.

Getting an error running webpack-dev-server. When I remove the html-webpack-plugin from my config it compiles fine, but keep getting the following error:

```
  TypeError: The 'compilation' argument must be an instance of Compilation
  
  - JavascriptModulesPlugin.js:116 Function.getCompilationHooks
    [irisroot]/[html-webpack-plugin]/[webpack]/lib/javascript/JavascriptModulesPlugin.js:116:10
  
  - NodeTemplatePlugin.js:34 compiler.hooks.thisCompilation.tap.compilation
    [irisroot]/[html-webpack-plugin]/[webpack]/lib/node/NodeTemplatePlugin.js:34:42
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [iris]/[tapable]/lib/Hook.js:14:14
  
  - Compiler.js:864 Compiler.newCompilation
    [iris]/[webpack]/lib/Compiler.js:864:30
  
  - Compiler.js:905 hooks.beforeCompile.callAsync.err
    [iris]/[webpack]/lib/Compiler.js:905:29
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [iris]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:900 Compiler.compile
    [iris]/[webpack]/lib/Compiler.js:900:28
  
  - Compiler.js:445 Compiler.runAsChild
    [iris]/[webpack]/lib/Compiler.js:445:8
  
  - child-compiler.js:110 compilationPromise.Promise
    [irisroot]/[html-webpack-plugin]/lib/child-compiler.js:110:21
  
  - new Promise
  
  - child-compiler.js:109 HtmlWebpackChildCompiler.compileTemplates
    [irisroot]/[html-webpack-plugin]/lib/child-compiler.js:109:31
  
  - cached-child-compiler.js:344 PersistentChildCompilerSingletonPlugin.compileEntries
    [irisroot]/[html-webpack-plugin]/lib/cached-child-compiler.js:344:21
  
  - cached-child-compiler.js:211 isCacheValidPromise.then
    [irisroot]/[html-webpack-plugin]/lib/cached-child-compiler.js:211:47
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  
  - loader.js:834 Function.Module.runMain
    internal/modules/cjs/loader.js:834:11
  
  - node.js:283 startup
    internal/bootstrap/node.js:283:19
  
  - node.js:622 bootstrapNodeJSCore
    internal/bootstrap/node.js:622:3
  
Html Webpack Plugin:
```

## Environment

Node.js v10.16.3
darwin 18.7.0
npm 6.9.0
yarn 1.22.0
html-webpack-plugin@4.3.0  extraneous
webpack@5.0.0-beta.16

### Config

```
    new HtmlWebpackPlugin({
      template: '../index.html',
    }),
```

It seems to just have a problem with this project. I tried to get a minimal repo going, except it works fine there. Not sure what's going on within this project, but I've been trying to remove other things to see if it's something else without any luck.

**Comment by artola** [comment] 2020-06-02 19:12
@ebuchmann I had a similar error and it was because of having "webpack" installed in 2 places (monorepo), in such case it trigger this error (just having 1 works). Therefore, at least in my case, it is related to the node resolution.

**Comment by biggu0** [comment] 2020-07-30 12:11
> @ebuchmann I had a similar error and it was because of having "webpack" installed in 2 places (monorepo), in such case it trigger this error (just having 1 works). Therefore, at least in my case, it is related to the node resolution.

thx a lot !

**Comment by tianyingchun** [comment] 2020-09-12 02:08
what's progress of this issue ? i faced the same issue of "webpack": "^5.0.0-beta.30",

**Comment by hubcarl** [comment] 2020-09-12 14:17
I  faced the same issue of "webpack": "^5.0.0-beta.30"

**Comment by chunlai996** [comment] 2020-10-14 04:01
> what's progress of this issue ? i faced the same issue of "webpack": "^5.0.0-beta.30",

upgrade webpack to 5.1.0

**Comment by tianyingchun** [comment] 2020-10-17 11:03
@chunlai996  i upgrade to webpack@5.1.3 & html-webpack-plugin@next (alpha.5) it also throw this issue.

```
TypeError: The 'compilation' argument must be an instance of Compilation\n
```

**Comment by Thebarda** [comment] 2020-10-17 11:24
I don't have this kind of error using webpack@5.1.3, webpack-cli@4.0.0 and html-webpack-plugin@5.0.0-alpha.5.
Here is my config

**Comment by jantimon** [comment] 2020-10-17 21:24
I have also troubles to reproduce this issue

**Comment by tianyingchun** [comment] 2020-10-18 01:39
@jantimon @Thebarda i have just remove all plugins, just remain
```
new HtmlWebpackPlugin({
      template: 'a/b/index.html',
      filename: join(pkgDir.sync(__dirname) || '', 'templates/index-prod.html'),
    }),
```
it still throw this error, if remove `webpack-html-plugin` the build works fine. i don't know the reason, i prepare the simple repo to reproduce this issue later.

**Comment by tianyingchun** [comment] 2020-10-18 01:40
BTW i don't use `webpack-cli` i use `webpack` build api
```
//  multi compiler or single compiler.
  webpack(multiConfiguration[0], (err, stats) => {
if (err) {
        // Handle errors here
        return reject(err);
      }
      if (err) {
        return reject(err);
      }
      const { errors, warnings } = stats?.toJson();
      if (errors.length) {
        return reject(errors);
      }
      if (warnings.length) {
        return reject(warnings);
      }
      resolve({});
}
```

**Comment by jantimon** [comment] 2020-10-18 04:19
can you add a console log where the error occurs and output `compilation`?

**Comment by tianyingchun** [comment] 2020-10-18 09:17
@jantimon i try to start new repo with simplify webpack configurations to reproduce issue, but surprised it work fine can build success without errors, does not report me a error, the repo is `https://github.com/tianyingchun/webpack5`

Maybe i need to some more time to  investigate for this, be cause my real project is more complex than this ` demo repo.`

**Comment by tianyingchun** [comment] 2020-10-18 13:14
@jantimon i found how to reproduce this issue, if i put create `Html-webpack-plugin` instance into another npm module e.g. please consider below structures.

in repo `webpack-utils` expose method `createHtmlWebpackPlugin()`
```
 export const createHtmlWebpackPlugin = () =>{
   const htmlPlugins: [];
   htmlPlugins.push(new HtmlWebpackPlugin({});
   return htmlPlugin;
}
```

in repo `myProjects` 
import {createHtmlWebpackPlugin} from 'webpack-utils';
const webpack  = {
mode:'production',
......
plugins: createHtmlWebpackPlugin(),
....
};

and then run the webpack build it will throw errors.

if i copy all codes `createHtmlWebpackPlugin()` from `webpack-utils` into `myProjects` directly, it works fine.  

Why ? Or is there a wrong while in usage of plugin of `webpack`?

**Comment by radiogron** [comment] 2020-10-18 16:47
Got same problem. But with another config. Fir project I'm using gulp with webpack-stream and keep config into one file (gulpfile). There are only Vue loaders, styles and nothing else. Problem git during updating to new Vue 3, Vuex and also upgraded webpack from 4 to 5.

Fixed by downgrading webpack to 4th.

**Comment by jantimon** [comment] 2020-10-18 16:59
I believe this might happen if multiple different webpack versions are installed - if webpack uses instanceOf to verify the passed values it might fail because compilation was constructed with a foreign Compilation constructor

**Comment by tianyingchun** [comment] 2020-10-19 00:28
@jantimon no the two modules have the same version of  `wbpack` & `html-webpack-plugin`, even if i use `peerDependency` for `utils` module it also throw this error.

**Comment by jantimon** [comment] 2020-10-19 07:11
Can you please try to find the reason of this problem using `node --inspect-brk ./node_modules/.bin/webpack` and `debugger` statements?

**Comment by tianyingchun** [comment] 2020-10-19 08:04
:) i totally migrate my code into single repo now, keep `html-webpack-plugin` with `webpack` within the same `npm` `module`  it works fine :) when I have time, i will try to debug it, MAYBE this issue is related for `learna` package with `paths` definitions of tsconfig.json.

**Comment by spamshaker** [comment] 2020-10-19 17:43
I faced the same issue. Webpack shows a banner, which says that plugin does something on Compilation.asset hook while it is not supported anymore 
```
(node:16680) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

**Comment by ChrisAckerman** [comment] 2020-10-20 04:32
Can confirm. The issue can be reproduced in yarn workspaces if webpack-dev-server a transitive dependency and is _not hoisted_. This is not an issue in webpack@^4 (all other dependency versions identical at latest release version).

**Comment by tw19920521** [comment] 2020-10-20 07:09
solved? I have the same problem

**Comment by tw19920521** [comment] 2020-10-20 07:10
ERROR in TypeError: The 'compilation' argument must be an instance of Compilation

  - JavascriptModulesPlugin.js:118 getCompilationHooks
    [webpack_demo]/[webpack]/lib/javascript/JavascriptModulesPlugin.js:118:10

  - CommonJsChunkFormatPlugin.js:30 compiler.hooks.thisCompilation.tap.compilation
    [webpack_demo]/[webpack]/lib/javascript/CommonJsChunkFormatPlugin.js:30:19


  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [npm]/[webpack]/[tapable]/lib/Hook.js:14:14

  - Compiler.js:915 Compiler.newCompilation
    [npm]/[webpack]/lib/Compiler.js:915:30

  - Compiler.js:957 hooks.beforeCompile.callAsync.err
    [npm]/[webpack]/lib/Compiler.js:957:29


  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [npm]/[webpack]/[tapable]/lib/Hook.js:18:14

  - Compiler.js:952 Compiler.compile
    [npm]/[webpack]/lib/Compiler.js:952:28

  - Compiler.js:477 Compiler.runAsChild
    [npm]/[webpack]/lib/Compiler.js:477:8

webpack 5.0.0 compiled with 1 error in 1412 ms

**Comment by jantimon** [comment] 2020-10-22 08:20
I guess there is no way how we could solve this on html-webpack-plugin side..

**Comment by park1992** [comment] 2020-10-24 15:07
Download the 4 version of webpack try, 5 version changed a lot of content

**Comment by Misstear** [comment] 2020-10-26 13:14
npx webpack

**Comment by zx870283980** [comment] 2020-10-27 03:16
还是有这样的问题，需要怎么解决
![image](https://user-images.githubusercontent.com/32995846/97252833-e0e75880-1845-11eb-8ce2-d781e8bf8bf4.png)
![image](https://user-images.githubusercontent.com/32995846/97252848-e8a6fd00-1845-11eb-8214-8ea76dec38a4.png)

**Comment by jantimon** [comment] 2020-10-27 07:55
This is the new code in webpack 5 which is causing the problem:

https://github.com/webpack/webpack/blob/92cb047a9cb7eb71823cfbf4a9c4d6367bbb5166/lib/javascript/JavascriptModulesPlugin.js#L112-L122

`compilation instanceof Compilation` returns false if multiple webpack versions are installed (e.g. inside a mono repository)

**Closed** 2020-10-27 07:56 UTC

**Comment by jantimon** [comment] 2020-11-01 12:15
Probably fixed in `html-webpack-plugin@5.0.0-alpha.8` please repoen this issue if it's not fixed.

**Comment by theVoogie** [comment] 2020-11-02 14:19
Hi, I faced the same issue and tried almost every possible permutation of the configuration settings explained here. My dev dependencies are:

```
    "html-webpack-plugin": "^4.5.0",
    "webpack": "^5.3.1",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
```

And the fun part is that this was working on one Windows machined and giving the `The 'compilation' argument must be an instance of Compilation` error on other.

The solution was as simple as running the terminal as **administrator** for running the npm commands (`npm i`, `npm start`). 

I hope this will help someone to save some time :)

**Comment by jantimon** [comment] 2020-11-02 14:32
@theVoogie the fix is not part of `"html-webpack-plugin": "^4.5.0",` can you please try `5.0.0-alpha.9` instead?

**Comment by Night-Day-X** [comment] 2020-11-05 04:31
It can be fixed using @5.0.0-alpha.9, but the <script> was introduced in the header

**Comment by jantimon** [comment] 2020-11-05 08:15
@Night-Day-X yes that's an performance improvement - you can change that back with the `scriptLoading` option

**Comment by Si3rr4wow** [comment] 2020-11-06 14:32
I can confirm `html-webpack-plugin@5.0.0-alpha.9` fixed this for me (monorepo with multiple webpacks at different versions, on Windows).

**Comment by Sherryboom** [comment] 2020-11-25 01:08
Got this issue too，with `vue-loader@15.9.5`,  avoided this by setting 

` "vue-loader": "^14.0.0",`

(maybe the last stable version) in `webpack.config.js`.

**Comment by mudin** [comment] 2020-12-03 08:28
This issue is not related to html-webpack-plugin. It is happening even I don't use it
