### ISSUE TITLE
Error: webpack:///data:text/javascript,__webpack_public_path___=___webpack_base_uri___=_htmlWebpackPluginPubl icPath;

### ISSUE THREAD

**Issue by huokd** [jantimon/html-webpack-plugin#1640] opened 2021-04-23 15:30 UTC
```
assets by status 385 KiB [cached] 1 asset
asset index.html 1.3 KiB [emitted]
runtime modules 1.19 KiB 5 modules
modules by path ./src/ 5.38 KiB
  modules by path ./src/*.vue 1.9 KiB 5 modules
  modules by path ./src/views/*.vue 1.91 KiB 5 modules
  ./src/main.js 510 bytes [built] [code generated]
  ./src/router/index.js 613 bytes [built] [code generated]
  ./src/store/index.js 491 bytes [built] [code generated]
modules by path ./node_modules/ 342 KiB
  ./node_modules/vue/dist/vue.runtime.esm.js 222 KiB [built] [code generated]
  ./node_modules/vue-loader/lib/runtime/componentNormalizer.js 2.71 KiB [built] [code generated]
  ./node_modules/vue-router/dist/vue-router.esm.js 80.7 KiB [built] [code generated]
  ./node_modules/vuex/dist/vuex.esm.js 36.4 KiB [built] [code generated]

ERROR in   Error: webpack:///data:text/javascript,__webpack_public_path___=___webpack_base_uri___=_htmlWebpackPluginPubl
icPath;?:  2
  __webpack_require__.p = __webpack_base_uri__ = htmlWebpackPluginPublicPath;
                                               ^
  ReferenceError: __webpack_base_uri__ is not defined

  - javascript,__webpack_public_path___=___webpack_base_uri___=_htmlWebpackPluginPublicPath;?:2 eval
    webpack:///data:text/javascript,__webpack_public_path___=___webpack_base_uri___=_htmlWebpackPluginPublicPath;?:2:46

  - index.html:36 Object.data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPa
    th;
    C:/Users/Administrator/Desktop/vue/public/index.html:36:1

  - index.html:59 __webpack_require__
    C:/Users/Administrator/Desktop/vue/public/index.html:59:41

  - index.html:86
    C:/Users/Administrator/Desktop/vue/public/index.html:86:11

  - index.html:88
    C:/Users/Administrator/Desktop/vue/public/index.html:88:12

  - index.js:142 HtmlWebpackPlugin.evaluateCompilationResult
    [vue]/[html-webpack-plugin]/index.js:142:28

  - index.js:324
    [vue]/[html-webpack-plugin]/index.js:324:26

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - async Promise.all
```

**Comment by mokSingh** [comment] 2021-04-30 09:56
Moving back to  "html-webpack-plugin": "^4.0.0" resolved the issue for me.

**Comment by Pavel910** [comment] 2021-05-02 14:53
@mokSingh going back to `4.0.0` is not a solution, as it now prints deprecations warnings and warns of breaking changes:
```
// "html-webpack-plugin": "^4.5.2"
(node:4968) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are dep
recated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

With v5 however, it emits a weird asset:
```
// "html-webpack-plugin": "^5.3.1",
asset static/media/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;.1feff74f.bin 77 bytes [emitted]
```

**Comment by jantimon** [comment] 2021-05-02 17:51
I can't analyse this issue without more information..  
Please don't delete the issue template

This seems to be a duplicate of https://github.com/jantimon/html-webpack-plugin/issues/1589#issuecomment-830845614

**Closed by jantimon** 2021-05-02 17:51 UTC
