### ISSUE TITLE
after upgrade plugin to v4.x.x occur error:ROR in The "path" argument must be of type string. Received type object, 

### ISSUE THREAD

**Issue by cn-fanfare** [jantimon/html-webpack-plugin#1465] opened 2020-06-10 11:54 UTC
[0] multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/video/index.js 52 bytes {video} [built]
    [./node_modules/webpack-dev-server/client/index.js?http://localhost:8081] (webpack)-dev-server/client?http://localhost:8081 4.29 KiB {video} [built]
    [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {video} [built]
    [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {video} [built]
    [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {video} [built]
    [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {video} [built]
    [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {video} [built]
    [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {video} [built]
    [./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {video} [built]
    [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {video} [built]
    [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {video} [built]
    [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {video} [built]
    [./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {video} [built]
    [./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {video} [built]
    [./src/video/index.js] 328 bytes {video} [built]
        + 21 hidden modules
    
    ERROR in The "path" argument must be of type string. Received an instance of Object
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    
    ERROR in   Error: Child compilation failed:
      The "path" argument must be of type string. Received an instance of Object
    
      - child-compiler.js:122
        [webapp]/[html-webpack-plugin]/lib/child-compiler.js:122:18
    
      - Compiler.js:343
        [webapp]/[webpack]/lib/Compiler.js:343:11
    
      - Compiler.js:681
        [webapp]/[webpack]/lib/Compiler.js:681:15
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compiler.js:678
        [webapp]/[webpack]/lib/Compiler.js:678:31
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1423
        [webapp]/[webpack]/lib/Compilation.js:1423:35
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1414
        [webapp]/[webpack]/lib/Compilation.js:1414:32
    
    
      - Hook.js:154 AsyncSeriesHook.lazyCompileHook
        [webapp]/[tapable]/lib/Hook.js:154:20
    
      - Compilation.js:1409
        [webapp]/[webpack]/lib/Compilation.js:1409:36
    
    
    
    Child HtmlWebpackCompiler:
                              Asset      Size               Chunks  Chunk Names
        __child-HtmlWebpackPlugin_0  6.96 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
        __child-HtmlWebpackPlugin_1  5.43 KiB  HtmlWebpackPlugin_1  HtmlWebpackPlugin_1
        __child-HtmlWebpackPlugin_2  7.93 KiB  HtmlWebpackPlugin_2  HtmlWebpackPlugin_2
        __child-HtmlWebpackPlugin_3  8.15 KiB  HtmlWebpackPlugin_3  HtmlWebpackPlugin_3
        __child-HtmlWebpackPlugin_4  5.76 KiB  HtmlWebpackPlugin_4  HtmlWebpackPlugin_4
        __child-HtmlWebpackPlugin_5  9.61 KiB  HtmlWebpackPlugin_5  HtmlWebpackPlugin_5
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        Entrypoint HtmlWebpackPlugin_1 = __child-HtmlWebpackPlugin_1
        Entrypoint HtmlWebpackPlugin_2 = __child-HtmlWebpackPlugin_2
        Entrypoint HtmlWebpackPlugin_3 = __child-HtmlWebpackPlugin_3
        Entrypoint HtmlWebpackPlugin_4 = __child-HtmlWebpackPlugin_4
        Entrypoint HtmlWebpackPlugin_5 = __child-HtmlWebpackPlugin_5
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/base.jsp] 977 bytes {HtmlWebpackPlugin_0} [built]
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/foot.jsp] 400 bytes {HtmlWebpackPlugin_1} [built]
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/head.jsp] 1.4 KiB {HtmlWebpackPlugin_2} [built]
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/page.jsp] 1.47 KiB {HtmlWebpackPlugin_3} [built]
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/video/index.jsp] 485 bytes {HtmlWebpackPlugin_4} [built]
        [./node_modules/html-webpack-plugin/lib/loader.js!./src/video/rtc.jsp] 1.92 KiB {HtmlWebpackPlugin_5} [built]
    
        ERROR in The "path" argument must be of type string. Received an instance of Object
    i ｢wdm｣: Failed to compile.

**Comment by cn-fanfare** [comment] 2020-06-13 12:12
why?

**Comment by cn-fanfare** [comment] 2020-06-13 12:39
how to fix this?

**Comment by jantimon** [comment] 2020-06-13 13:00
Sorry I don’t know from that stack trace - what have you already done to analyze the problem?

**Comment by cn-fanfare** [comment] 2020-06-15 10:39
{
    "name": "webapp",
    "version": "1.0.0",
    "description": "Webpack5",
    "main": ".eslintrc.js",
    "directories": {
        "bin": "./bin",
        "lib": "./lib"
    },
    "files": [
        "bin/",
        "lib/"
    ],
    "scripts": {
        "merge": "cross-env NODE_ENV=production node build/merge.js",
        "merge:dev": "cross-env NODE_ENV=development node build/merge.js",
        "build": "cross-env NODE_ENV=production node build/build.js",
        "dev": "cross-env NODE_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.js",
        "start": "npm run dev",
        "prettier:webapp": "prettier --loglevel warn --write \"*.(js|json)\"",
        "prettier:build": "prettier --loglevel warn --write \"build/**/*.(js|json)\"",
        "prettier:src": "prettier --loglevel warn --write \"src/**/*.(js|json)\"",
        "eslint:webapp": "eslint --fix *.js",
        "eslint:build": "eslint --fix build/**/*.js",
        "eslint:src": "eslint --fix src/**/*.js",
        "test": "node test/run.js"
    },
    "keywords": [],
    "author": "li+gu+sheng",
    "license": "ISC",
    "devDependencies": {
        "@babel/core": "^7.10.2",
        "@babel/plugin-transform-runtime": "^7.10.1",
        "@babel/preset-env": "^7.10.2",
        "autoprefixer": "^9.8.0",
        "babel-eslint": "^10.1.0",
        "babel-loader": "^8.1.0",
        "browserslist": "^4.12.0",
        "chalk": "^4.1.0",
        "clean-webpack-plugin": "^3.0.0",
        "compression-webpack-plugin": "^4.0.0",
        "copy-webpack-plugin": "^6.0.2",
        "cross-env": "^7.0.2",
        "css-loader": "^3.6.0",
        "csso": "^4.0.3",
        "dateformat": "^3.0.3",
        "eslint": "^7.2.0",
        "eslint-config-prettier": "^6.11.0",
        "eslint-formatter-friendly": "^7.0.0",
        "eslint-loader": "^4.0.2",
        "eslint-plugin-import": "^2.21.2",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-prettier": "^3.1.4",
        "friendly-errors-webpack-plugin": "^1.7.0",
        "fs-extra": "^9.0.1",
        "glob": "^7.1.6",
        "html-webpack-plugin": "^4.3.0",
        "mini-css-extract-plugin": "^0.9.0",
        "node-notifier": "^7.0.1",
        "npm-check-updates": "^7.0.1",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "ora": "^4.0.4",
        "portfinder": "^1.0.26",
        "postcss": "^7.0.32",
        "postcss-import": "^12.0.1",
        "postcss-loader": "^3.0.0",
        "postcss-url": "^8.0.0",
        "prettier": "^2.0.5",
        "raw-loader": "^4.0.1",
        "terser": "^4.7.0",
        "terser-webpack-plugin": "^3.0.4",
        "webpack": "^4.43.0",
        "webpack-bundle-analyzer": "^3.8.0",
        "webpack-cli": "^3.3.11",
        "webpack-dev-server": "^3.11.0",
        "webpack-merge": "^4.2.2",
        "write-file-webpack-plugin": "^4.5.1"
    },
    "dependencies": {
        "@babel/runtime": "^7.10.2",
        "blob-util": "^2.0.2",
        "crypto-js": "^4.0.0",
        "jquery": "^3.5.1",
        "jquery-migrate": "^3.3.0",
        "recordrtc": "^5.6.1",
        "video.js": "^7.8.2",
        "videojs-markers-plugin": "^1.0.2",
        "videojs-record": "^4.0.0"
    },
    "engines": {
        "node": ">=12.0.0"
    }
}

package.json

**Comment by cn-fanfare** [comment] 2020-06-15 10:40
v3 is ok, but v4 occur error.

**Comment by cn-fanfare** [comment] 2020-06-15 10:41
wepack/lib/Compiler.js 675 compilation.seal occur error.

**Comment by cn-fanfare** [comment] 2020-06-15 11:01
{
    "cache": {
        "type": "filesystem"
    },
    "context": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp",
    "entry": {
        "video": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\video\\index.js"
    },
    "output": {
        "publicPath": "/Webpack5",
        "path": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test",
        "filename": "static/js/[name].js?[hash]",
        "chunkFilename": "static/js/[id].js?[hash]"
    },
    "stats": {
        "errorDetails": true
    },
    "module": {
        "rules": [
            {
                "enforce": "pre",
                "test": {},
                "exclude": {},
                "use": {
                    "loader": "eslint-loader",
                    "options": {
                        "fix": true,
                        "cache": true,
                        "emitError": true,
                        "emitWarning": true
                    }
                }
            },
            {
                "test": {},
                "exclude": {},
                "use": {
                    "loader": "babel-loader",
                    "options": {
                        "cacheDirectory": true
                    }
                }
            },
            {
                "test": {},
                "use": [
                    {
                        "loader": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\node_modules\\mini-css-extract-plugin\\dist\\loader.js",
                        "options": {
                            "hmr": true,
                            "reloadAll": true
                        }
                    },
                    {
                        "loader": "css-loader",
                        "options": {
                            "importLoaders": 1
                        }
                    },
                    {
                        "loader": "postcss-loader"
                    }
                ]
            },
            {
                "test": {},
                "use": [
                    {
                        "loader": "raw-loader",
                        "options": {
                            "esModule": false
                        }
                    }
                ]
            }
        ]
    },
    "plugins": [
        {
            "options": {
                "filename": "static/css/[name].css?[hash]",
                "ignoreOrder": false,
                "chunkFilename": "static/css/[id].chunk.css?[hash]"
            }
        },
        {
            "patterns": [
                {
                    "from": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\static",
                    "to": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\static",
                    "globOptions": {
                        "dot": true,
                        "gitignore": true,
                        "ignore": [
                            ".*"
                        ]
                    }
                }
            ],
            "options": {}
        },
        {
            "dangerouslyAllowCleanPatternsOutsideProject": false,
            "dry": false,
            "verbose": false,
            "cleanStaleWebpackAssets": false,
            "protectWebpackAssets": true,
            "cleanAfterEveryBuildPatterns": [],
            "cleanOnceBeforeBuildPatterns": [
                "static/**/*",
                "WEB-INF/pages/**/*",
                "*.hot-update.js",
                "*.hot-update.json"
            ],
            "currentAssets": [],
            "initialClean": false,
            "outputPath": ""
        },
        {},
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\base.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\base.jsp",
                "hash": false,
                "inject": false,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": null,
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\foot.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\foot.jsp",
                "hash": false,
                "inject": false,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": null,
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\head.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\head.jsp",
                "hash": false,
                "inject": false,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": null,
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\page.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\page.jsp",
                "hash": false,
                "inject": false,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": null,
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\video\\index.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\video\\index.jsp",
                "hash": false,
                "inject": true,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": [
                    "video"
                ],
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {
                "template": "E:\\lgs\\dev\\workspace\\Webpack5\\webapp\\src\\video\\rtc.jsp",
                "templateContent": false,
                "filename": "E:\\lgs\\dev\\workspace\\.metadata\\.plugins\\org.eclipse.wst.server.core\\tmp0\\wtpwebapps\\Test\\WEB-INF\\pages\\video\\rtc.jsp",
                "hash": false,
                "inject": false,
                "scriptLoading": "blocking",
                "compile": true,
                "favicon": false,
                "minify": false,
                "cache": true,
                "showErrors": true,
                "chunks": null,
                "excludeChunks": [],
                "chunksSortMode": "auto",
                "meta": {},
                "base": false,
                "title": "Webpack App",
                "xhtml": false
            },
            "version": 4
        },
        {
            "options": {},
            "fullBuildTimeout": 200,
            "requestTimeout": 10000
        },
        {
            "compilationSuccessInfo": {
                "messages": [
                    "Your application is running here: http://localhost:8081"
                ]
            },
            "shouldClearConsole": true,
            "formatters": [
                null,
                null,
                null
            ],
            "transformers": [
                null,
                null,
                null
            ]
        }
    ],
    "mode": "development",
    "devtool": "cheap-module-eval-source-map",
    "devServer": {
        "clientLogLevel": "warning",
        "historyApiFallback": true,
        "hot": true,
        "contentBase": false,
        "compress": true,
        "host": "localhost",
        "port": 8081,
        "open": false,
        "overlay": {
            "warnings": true,
            "errors": true
        },
        "publicPath": "/Webpack5",
        "proxy": {},
        "watchOptions": {
            "poll": false
        },
        "quiet": false
    }
}

webpack config file output file to json.

**Comment by cn-fanfare** [comment] 2020-06-16 14:38
anyone at here?

**Comment by syaitskyi** [comment] 2020-06-26 10:53
@cn-fanfare Hi, mate, I don't know if it's still relevant to you, but the problem is not with `html-webpack-plugin`.
I see in your package.json that you have installed `copy-webpack-plugin@6.0.2`. To solve your issue try to downgrade package to at least `copy-webpack-plugin@5.1.1`. You need to change config you passed to that plugin as it mentioned [here](https://github.com/webpack-contrib/copy-webpack-plugin/tree/v5.1.1#getting-started).

[Original issue is related to the `globby`](https://github.com/sindresorhus/globby/issues/145)

**Comment by cn-fanfare** [comment] 2020-06-28 08:31
@syaitskyi you right, but why the stack trace output html-webpack-plugin occur error ?

**Comment by syaitskyi** [comment] 2020-06-28 10:58
idk, seems like 'unhandled promise rejection' bubbles up and stack trace cough that error on the html plugin step. This is only my assumption.

**Comment by cn-fanfare** [comment] 2020-06-30 09:19
Thanks!

**Comment by evilebottnawi** [comment] 2020-06-30 11:51
@jantimon We can close this issue in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/496

**Closed** 2021-06-26 02:57 UTC
Labels: wontfix
