### ISSUE TITLE
Using custom template and <%= htmlWebpackPlugin.options.title %> stalls the build

### ISSUE THREAD

**Issue by pke** [jantimon/html-webpack-plugin#612] opened 2017-03-10 21:50 UTC
I am using 
```html
<title><%= htmlWebpackPlugin.options.title %></title>
```

with this config:

```es6
new HtmlWebpackPlugin({
      title: PRODUCT,
      template: "./src/index.html",
      inject: "body",
    }),
```

the webpack never finishes. If I remove the `<%= htmlWebpackPlugin.options.title %>` it does.
using: `html-webpack-plugin@2.16.0`

**Comment by mastilver** [comment] 2017-05-20 09:30
@pke @selbekk I could not reproduce on my local setup

Would you please setup a repository that reproduces the issue

**Comment by mastilver** [comment] 2017-05-30 10:10
I'm closing this down as I didn't hear back from you

If you still think that's an issue, please reach back here! :)

**Closed by mastilver** 2017-05-30 10:10 UTC
