### ISSUE TITLE
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [jantimon/html-webpack-plugin#1523] opened 2020-10-05 00:02 UTC
"webpack": "^5.0.0-rc.3",

```
> node --trace-deprecation scripts/build.js

(node:3436) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at C:\localhost\maxmaxmaximus\node_modules\html-webpack-plugin\index.js:280:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by martinoppitz** [comment] 2020-10-06 20:10
What's the problem?!

**Comment by ronanyeah** [comment] 2020-10-13 13:16
https://github.com/jantimon/html-webpack-plugin/issues/1501

**Comment by jantimon** [comment] 2020-10-16 08:20
Can you please see if this is fixed with html-webpack-plugin@5.0.0-alpha.2 ?  
Please see also #1527

**Comment by grgur** [comment] 2020-10-16 10:50
It looks good in the latest `alpha.3`. Thanks @jantimon

**Comment by jantimon** [comment] 2020-10-16 11:01
Thanks for testing 👍

**Comment by SadeghShaikhi** [comment] 2020-10-17 14:37
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**Comment by yumindeckard** [comment] 2020-10-17 20:51
Same here.

**Comment by jantimon** [comment] 2020-10-17 21:09
Which version did you use?

**Comment by jantimon** [comment] 2020-10-17 21:27
Can you please try [html-webpack-plugin@5.0.0-alpha.6](https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.6)?

**Comment by bigskillet** [comment] 2020-10-18 03:54
Alpha.6 seems to have removed the warning for me.

**Comment by SadeghShaikhi** [comment] 2020-10-18 11:21
> Alpha.6 seems to have removed the warning for me.

same here, no warning with alpha 6

**Comment by jantimon** [comment] 2020-10-18 17:03
thanks for the testing feedback 👍

**Closed** 2020-10-18 17:03 UTC

**Comment by michalmuchakr** [comment] 2020-10-24 19:51
Hi, updating my project to webpack 5, here is my config:

`    "webpack": "^5.2.0",
    "webpack-assets-manifest": "3.1.1",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
`

`emitting emit(node:14228) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.`

**Comment by borm** [comment] 2020-11-01 12:31
```
 [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
```

**Comment by jantimon** [comment] 2020-11-01 12:43
> ```
> 
>  [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
> 
> ```

Which version did you use?

Can you please try https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.9

**Comment by Yijx** [comment] 2020-11-02 03:19
> > ```
> > 
> >  [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
> > ```
> 
> Which version did you use?
> 
> Can you please try https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.9

5.0.0-alpha.7 is Ok, no warning. But 5.0.0-alpha.9 has this warning.

**Comment by uniquemo** [comment] 2020-11-02 06:42
> > > ```
> > > 
> > >  [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
> > > ```
> > 
> > 
> > Which version did you use?
> > Can you please try https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.9
> 
> 5.0.0-alpha.7 is Ok, no warning. But 5.0.0-alpha.9 has this warning.
> ![image](https://user-images.githubusercontent.com/30200703/97826767-762e9500-1cfd-11eb-8765-f45ff0d3a8b6.png)

I encounter the same problem~ also version 5.0.0-alpha.9

**Comment by Justin-YAA** [comment] 2020-11-02 07:46
> > ```
> > 
> >  [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
> > ```
> 
> Which version did you use?
> 
> Can you please try https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.9

Same here, having the same warning with 5.0.0-alpha.9
![image](https://user-images.githubusercontent.com/70956087/97842372-cef33300-1ce7-11eb-9ca6-a7385f299c89.png)

**Comment by jantimon** [comment] 2020-11-02 08:23
Thanks for your feedback - switched to EntryPlugin for [html-webpack-plugin/v/5.0.0-alpha.10](https://www.npmjs.com/package/html-webpack-plugin/v/5.0.0-alpha.10)

**Comment by amirHossein-Ebrahimi** [comment] 2020-11-05 14:19
thanks for your works, but still have depreciation warnings with the latest versions
```bash
[DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

## installed packages
```json
{
  "html-webpack-plugin": "^5.0.0-alpha.10",
  "webpack": "^5.4.0"
}
```

**Comment by jantimon** [comment] 2020-11-05 14:32
@amirHossein-Ebrahimi it looks like you using the wrong html-webpack-plugin version - alpha 10 has no SingleEntryPlugin but only EntryPlugin:

https://unpkg.com/html-webpack-plugin@5.0.0-alpha.10/lib/child-compiler.js

**Comment by amirHossein-Ebrahimi** [comment] 2020-11-05 14:44
@jantimon yarn.lock is updated to the specified version `^5.0.0-alpha.10`.
I'm going to test it (and install all packages again :cry: )

**Comment by amirHossein-Ebrahimi** [comment] 2020-11-05 15:00
@jantimon you were right in the `SingleEntryPlugin` case it is not a case with `html-webpack-plugin`

thank you :pray:

**Comment by surielmx** [comment] 2020-11-13 03:47
Same issue, but...

Before update to `5.0.0-alpha.14`
![Screen Shot 2020-11-12 at 21 42 45](https://user-images.githubusercontent.com/1803166/99026230-24bdab80-2530-11eb-814d-4fcb040cb26b.png)

After update to `5.0.0-alpha.14`
![Screen Shot 2020-11-12 at 21 31 46](https://user-images.githubusercontent.com/1803166/99026268-37d07b80-2530-11eb-82da-7b86bd5ca7be.png)

What I using...
![code](https://user-images.githubusercontent.com/1803166/99026430-89790600-2530-11eb-915f-a725a86f1c71.png)

It's related to `html-webpack-plugin` ?

**Comment by jantimon** [comment] 2020-11-13 08:09
@surielmx it's hard to tell as you have sooo many plugins and npm packages which could also cause this issue - can you try to remove all which are unrelated for the html generation and try again e.g. 'webpack-merge', 'babel', 'eslint', 'file-loader', 'open'....

**Comment by mauriziocescon** [comment] 2020-11-13 17:13
@surielmx I guess it might be related to the output. Tty something like:

```    
output: {
   path: path.resolve(__dirname, '../dist'),
   filename: '[name].[fullhash].js',
},
```

**Comment by mauriziocescon** [comment] 2020-11-13 18:04
Hi @jantimon! 

I have issues as well (webpack 5). Here is my [toy-app (dev branch)](https://github.com/mauriziocescon/react-app/tree/develop) with `"html-webpack-plugin": "5.0.0-alpha.14"`. When I build (`npm run build`) I get the following error: 

`ERROR in Conflict: Multiple assets emit different content to the same filename index.html`

Any idea what's going wrong? 



As you can see, I have many plugins... but I think It's coming from HtmlWebpackPlugin cause in [toy-app (master)](https://github.com/mauriziocescon/react-app/tree/master) with `"html-webpack-plugin": "4.5.0"` I get the warning mentioned by the others above (no errors). 

With 4.5.0 the build script is fine (just the deprecation warning), but when I try to serve the app with `webpack serve` and modify the files I see index.html is empty... so no resources added. In other words, `webpack serve` is useless for development. 

![Screenshot 2020-11-13 at 18 46 25](https://user-images.githubusercontent.com/3672842/99105428-cef60b80-25e2-11eb-939a-5d34f8034ae7.png)

**Comment by surielmx** [comment] 2020-11-13 18:46
Thank you @mauriziocescon, `filename: '[name].[fullhash].js'`  solves the problem.

**Comment by mauriziocescon** [comment] 2020-11-13 21:09
Great, thanks a lot @jantimon, it works fine! Indeed, you are right... I created the config some time ago with webpack 4. 
It wasn't a problem, but it doesn't make any sense copying index. 

Thanks! 

```
 new CopyPlugin({
        patterns: [
          // {from: 'src/index.html'}, DO NOT COPY index IF YOU USE HtmlWebpackPlugin
          {from: 'src/assets/i18n', to: 'assets/i18n'},
          {from: 'src/assets/imgs', to: 'assets/imgs'},
        ],
      }),

      // insert file dynamically
      new HtmlWebpackPlugin({
        template: 'src/index.html',
        inject: 'body',
      }),
```

**Comment by matthewegan** [comment] 2020-11-29 19:56
```zsh
webpack-html-boilerplate % cat yarn.lock | grep html-webpack-plugin
html-webpack-plugin@5.0.0-alpha.14:
  resolved "https://registry.yarnpkg.com/html-webpack-plugin/-/html-webpack-plugin-5.0.0-alpha.14.tgz#9c7f10da25371d13d76ad159923e49aa678a9542"
```
```zsh
webpack-html-boilerplate % yarn build
yarn run v1.22.10
$ webpack --config webpack.prod.js
(node:57415) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

**Comment by jantimon** [comment] 2020-11-30 09:31
This bug seems to be resolved - any other bugs are probably caused by other plugins.  
I'll lock this issue for now - please open a new issue if you find new bugs.
