### ISSUE TITLE
Fix npm dependencies

### ISSUE THREAD

**Issue by evanjmg** [jantimon/html-webpack-plugin#791] opened 2017-10-02 14:15 UTC
Related to  https://github.com/marcelklehr/toposort/issues/20
## Description
Please fix all your dependencies and test before updating, do not rely on other people's releases to keep things up to date.
```
Unhandled rejection Error: Cyclic dependency: "[object Object]" node_modules/toposort/index.js:32:13)
```

**Comment by NaveenKY** [comment] 2017-10-02 14:34
Try adding toposort@1.0.3 directly in your package.json as
----------------
"toposort": "1.0.3"

**Comment by evanjmg** [comment] 2017-10-02 14:35
1.0.4 works as well as a temporary fix, but the package.json on this repo needs to be fixed! Why is this library auto updating it's dependencies? They should all be fixed!

**Comment by NaveenKY** [comment] 2017-10-02 14:39
I agree with you, autoupdate should not be given in package.json for any 3rd party libraries.

**Comment by adammlr** [comment] 2017-10-02 14:40
I think this is also happening on the extract text webpack plugin

**Comment by SeeThruHead** [comment] 2017-10-02 14:42
toposort is not being a good citizen, and has a breaking change in a patch. locking deps isn't the solution really imo

**Comment by SeeThruHead** [comment] 2017-10-02 14:45
https://github.com/marcelklehr/toposort/issues/20#issuecomment-333555924

**Comment by evanjmg** [comment] 2017-10-02 14:48
I disagree, locking prevents others from breaking the library, but it looks like a revert went out. I understand the importance of trust, but when thousands of apps rely on html webpack, a quality assurance of versioning I think is important. Please consider fixing dependencies in the future

**Comment by damsorian** [comment] 2017-10-02 14:55
@evanjmg, I think this should not be closed, the fixing dependencies is a priority request to do.

**Comment by evanjmg** [comment] 2017-10-02 14:56
@damsorian I guess it's up to the contributors and owner to decide, I guess I can leave this open until some one else closes it.

**Comment by mastilver** [comment] 2017-10-02 16:29
I'm leaving @jantimon decide but I don't think libraries should fix their dependencies

If you want to be safe, then lock your dependencies on your side

Please read: https://github.com/sindresorhus/ama/issues/479

**Comment by jantimon** [comment] 2017-10-03 09:34
Totally agree with mastilver - maybe topsort could rollback and release the changes as a breaking change according to semver

**Comment by marcelklehr** [comment] 2017-10-03 13:07
First up: I'm very sorry for screwing things up royally. Yes, I did a rollback yesterday. The cause was a buggy PR that didn't get caught by the tests, but ultimately this likely wouldn't have affected this many people if I had followed semver to the point and released the new version as a minor release instead of a patch.

My two cents: Fixing deps is a difficult decision. I don't know the best way to go, there. Some people argue, there's more good than bad updates, others argue, if there is a bad update, you are safe if the deps are fixed. IMO, it depends on how dedicated the maintainer of the library is. If they frequently check their deps for updates, I think it's ok to fix them, if they don't, I'd rather they don't fix them. But then, what is "frequently"?

**Comment by mastilver** [comment] 2017-11-14 19:10
Thank you everyone for all your inputs!

And thank you @marcelklehr for `topsort`. Only the ones who never published their work, never published a bad release, it happens to the best of us! :)

So in conclusion, I'm closing this issue. As I said earlier, if you want fixed dependencies, just use a `npm-lock.json` or `yarn.lock`

**Closed by mastilver** 2017-11-14 19:10 UTC
