### ISSUE TITLE
Errors after changing the source code with webpack 5.0.0-beta.0

### ISSUE THREAD

**Issue by anatoliikarpiuk** [jantimon/html-webpack-plugin#1292] opened 2019-10-18 06:32 UTC
Crashes after changing the source code. Cannot read property get of undefined
![66913430-4989db80-f01d-11e9-8344-a187fa6cb89e](https://user-images.githubusercontent.com/29492274/67070814-b4f0bc00-f189-11e9-85bc-69ec1e3637f3.jpg)

```
Node.js v12.12.0
win32 10.0.18362
npm 6.10.3
webpack 5.0.0-beta.0
html-webpack-plugin 4.0.0-beta.8
```

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.join(__dirname, "/dist"),
    filename: "bundle.js"
  },
  module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: {
        loader: "babel-loader"
      },
    }]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    })
  ],
  devServer: {
    progress: true
  },
};
```

**Comment by kenotron** [comment] 2019-12-21 22:42
This looks like #1129 

A workaround here (really, a PR would be better):

> If anyone is looking for a quick solution, I can't vouch for the correctness of this but it seems to work for me. Install the `patch-package` NPM module and set the `postinstall` script [as instructed](https://github.com/ds300/patch-package#set-up). Then, create a directory named "patches" and a file named something like "html-webpack-plugin+4.0.0-beta.8.patch" with the following contents:
> 
> ```js
> diff --git a/node_modules/html-webpack-plugin/lib/compiler.js b/node_modules/html-webpack-plugin/lib/compiler.js
> index 8960360..2f431d7 100644
> --- a/node_modules/html-webpack-plugin/lib/compiler.js
> +++ b/node_modules/html-webpack-plugin/lib/compiler.js
> @@ -336,9 +336,9 @@ function isChildCompilerCacheOutdated (mainCompilation, childCompiler) {
>      return false;
>    }
>    // Check if any dependent file was changed after the last compilation
> -  const fileTimestamps = mainCompilation.fileTimestamps;
> +  const fileTimestamps = mainCompilation.fileSystemInfo._fileTimestamps;
>    const isCacheOutOfDate = childCompiler.fileDependencies.some((fileDependency) => {
> -    const timestamp = fileTimestamps.get(fileDependency);
> +    const timestamp = fileTimestamps.get(fileDependency).timestamp;
>      // If the timestamp is not known the file is new
>      // If the timestamp is larger then the file has changed
>      // Otherwise the file is still the same
> ```
> 
> Run `npx patch-package` and it will at least stop the build from crashing and seems to allow proper hot reloading when I edit things so far.

**Comment by kenotron** [comment] 2019-12-21 22:44
Another workaround patch from #1316:

> I had [patched](https://github.com/ds300/patch-package) my packages already, but it's more quick-and-dirty:
> [This change-comparison](https://github.com/PutziSan/html-webpack-plugin/compare/34d8aa572c7acc59c26f3b5d15bf489a07aa4c24..db1e0cb7aa89d23212cd87a8958566420002c24d) reflects the changes I've made locally, so everything is working fine with Webpack 5 again. I didn't really understand the previous caching algorithm and adapted it in the easiest way for me, that's certainly not right for all cases and needs to be looked at again. Also, it doesn't fit perfectly yet, because the first time you render it, it also returns that the cache is invalid.
> Unfortunately, I don't have time to understand or improve it any further. But if someone wants a (not perfect) solution with Webpack 5 for now, he can use my changes as a patch.
> [edit: added some code, that I forgot to commit]

**Comment by jantimon** [comment] 2020-03-24 09:48
Duplicate of #1129

**Closed by jantimon** 2020-03-24 09:48 UTC
