### ISSUE TITLE
ESI:include tags are not terminated in version 4.0.1

### ISSUE THREAD

**Issue by rvsia** [jantimon/html-webpack-plugin#1370] opened 2020-03-26 09:15 UTC
## Expected behaviour

`esi:include` tags are terminated. (please see example [here 3.1](https://www.w3.org/TR/esi-lang))

It was working correctly in 3.2.0.

```html
<!DOCTYPE html>
<html lang="en-US">

    <head>
        <meta charset="UTF-8">
        <title>Sources</title>
        <esi:include src="/beta/apps/chrome/snippets/head.html" />
    </head>

    <body>
        <esi:include src="/beta/apps/chrome/snippets/body.html" />
    <script type="text/javascript" src="/beta/apps/sources/js/App.js"></script></body>

</html>
```

## Current behaviour

`esi:include` tags are not terminated.

Built index.html

```html
<!doctype html><html lang="en-US"><head><meta charset="UTF-8"><title>Sources</title><esi:include src="/beta/apps/chrome/snippets/head.html"></head><body><esi:include src="/beta/apps/chrome/snippets/body.html"><script src="/beta/apps/sources/js/App.js"></script></body></html>
```

## Environment

```
Node.js v10.16.0
linux 5.5.8-200.fc31.x86_64
npm 6.9.0
sources-ui@1.1.0 /home/rvsianskz/insightsproject/sources-ui
└── webpack@4.42.1 
```

### Config

```js
const webpackConfig = {
    mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    devtool: false,
    optimization: {
        minimize: process.env.NODE_ENV === 'production'
    },
    entry: {
        App: config.paths.entry
    },
    output: {
        filename: 'js/[name].js',
        chunkFilename: 'js/[name].js',
        path: config.paths.public,
        publicPath: config.paths.publicPath
    },
    plugins: [
    new(require('write-file-webpack-plugin'))(),
    new(require('html-webpack-plugin'))({
        title: 'Sources',
        filename: 'index.html',
        template: path.resolve(__dirname, '../src/index.html')
    }),
    new webpack.DefinePlugin({
        'process.env.BASE_PATH': JSON.stringify(process.env.BASE_PATH || '/api'),
    }),
    new(require('html-replace-webpack-plugin'))([{
        pattern: '@@env',
        replacement: config.deploymentEnv
    }])
]
    resolve: {
        alias: { react: resolve(__dirname, '../node_modules', 'react') }
    }
};
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<html lang="en-US">

    <head>
        <meta charset="UTF-8">
        <title>Sources</title>
        <esi:include src="/@@env/chrome/snippets/head.html" />
    </head>

    <body>
        <esi:include src="/@@env/chrome/snippets/body.html" />
    </body>

</html>
```

## Relevant Links

-  [SOURCES UI](https://github.com/RedHatInsights/sources-ui) Project repository

**Comment by jantimon** [comment] 2020-03-26 09:34
Can you please try if `minify: false` solves your issue?

**Comment by rvsia** [comment] 2020-03-26 09:45
@jantimon Yeah, `minify: false` fixed that.

**Comment by jantimon** [comment] 2020-03-26 09:55
Cool do you think we should add "keep closing slash" to defaults?

**Comment by rvsia** [comment] 2020-03-26 09:58
I think we definitely should, when it's not reliable and it can break things. :+1:

**Comment by edmorley** [comment] 2020-03-26 10:04
Hi! The investigation for choice of options is here:
https://github.com/jantimon/html-webpack-plugin/issues/1036#issuecomment-421408841

It sounds like it would be worth also reporting this upstream to https://github.com/kangax/html-minifier since we're currently using the defaults it sets for `keepClosingSlash` (which is `false`) -- and it seems like the minifier should default to "safe" options.

**Comment by jantimon** [comment] 2020-03-26 10:13
thanks @edmorley for your fast response :)   
I hope you saw that you got credits for your efforts in the release blog post: https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d

I create a pull request (#1371) to fix that issue.

advantage: will fix problems for people using xml elements inside html  
disadvantage: if someone would add `<img .. />` it can't be minified anymore to `<img ...>`.

**Comment by edmorley** [comment] 2020-03-26 10:15
Yeah I did see that - that was very kind thank you :-)

Agree it's best to override the default pending a fix and/or default change upstream.

**Comment by jantimon** [comment] 2020-03-26 10:24
Released as html-webpack-plugin 4.0.2.  
@rvsia could you please ask @danielruf if that change should also be added to html-minifier-terser?

**Comment by rvsia** [comment] 2020-03-26 11:04
@jantimon Should I open an issue there?

**Comment by DanielRuf** [comment] 2020-03-26 12:14
> Agree it's best to override the default pending a fix and/or default change upstream.

It was always set to `false` by default as far as I am aware of it.

Changing the default of html-minifier and html-minifier-terser would be a breaking change.

https://github.com/kangax/html-minifier/commit/a04ca1f527c99b7d73e1f5a838c3e62140100916

So in this case I would have to bump the major version. As this was always set to false we should set it in html-webpack-plugin.

https://github.com/jantimon/html-webpack-plugin#minification

v3.2 used html-minifier ^3.2: https://github.com/jantimon/html-webpack-plugin/blob/v3.2.0/package.json#L49

The default value or behavior has not changed, see https://github.com/danielruf/html-minifier-terser/compare/v3.5.21..v5.0.5

**Comment by DanielRuf** [comment] 2020-03-26 12:17
In v3.2.0 of html-webpack-plugin `options.minify` seems to have been `true`.

https://github.com/jantimon/html-webpack-plugin/issues/1370#L117

https://github.com/jantimon/html-webpack-plugin/blob/d1b173f9442d01d814590f991ddcece81c8f0274/index.js#L116-L128

I fail to see how this is related to changes in html-minifier and html-minifier-terser.

https://github.com/jantimon/html-webpack-plugin/blob/v3.2.0/index.js#L314-L317

**Comment by edmorley** [comment] 2020-03-26 16:45
@DanielRuf Hi! I'm not saying that the html-minifier-terser / html-minifier defaults have changed. I'm saying that "if there is a bug with the defaults used by them, then either it would be good to fix the bug, or change that default". I agree changing that default would be a breaking change, so ideally it would be best to just fix the bug :-)

**Comment by DanielRuf** [comment] 2020-03-26 17:15
> I agree changing that default would be a breaking change, so ideally it would be best to just fix the bug

I see no bug in html-minifier / html-minifier-terser. Or do you mean regarding the missing self-closing slash?

Not sure if this is a bug as the html5 mode is used by default so self-closing tags are not needed.

Also see https://stackoverflow.com/a/7854998/753676

https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L71

```
// Empty Elements
var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr');
```

**Comment by DanielRuf** [comment] 2020-03-26 17:16
> I agree changing that default would be a breaking change, so ideally it would be best to just fix the bug

I see no bug in html-minifier / html-minifier-terser. Or do you mean regarding the missing self-closing slash?

Not sure if this is a bug as the html5 mode is used by default so self-closing tags are not needed.

Also see https://stackoverflow.com/a/7854998/753676

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L71

```
// Empty Elements
var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr');
```

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L76-L78

```
// Elements that you can, intentionally, leave open
// (and which close themselves)
var closeSelf = makeMap('colgroup,dd,dt,li,option,p,td,tfoot,th,thead,tr,source');
```

So I would say it is not a but and works as intended.

**Comment by DanielRuf** [comment] 2020-03-26 17:17
> I agree changing that default would be a breaking change, so ideally it would be best to just fix the bug

I see no bug in html-minifier / html-minifier-terser. Or do you mean regarding the missing self-closing slash?

Not sure if this is a bug as the html5 mode is used by default so self-closing tags are not needed.

Also see https://stackoverflow.com/a/7854998/753676

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L71

```
// Empty Elements
var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr');
```

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L76-L78

```
// Elements that you can, intentionally, leave open
// (and which close themselves)
var closeSelf = makeMap('colgroup,dd,dt,li,option,p,td,tfoot,th,thead,tr,source');
```

So I would say it is not a bug and works as intended.

**Comment by DanielRuf** [comment] 2020-03-26 17:18
> I agree changing that default would be a breaking change, so ideally it would be best to just fix the bug

I see no bug in html-minifier / html-minifier-terser. Or do you mean regarding the missing self-closing slash?

Not sure if this is a bug as the html5 mode is used by default so self-closing tags are not needed and there are only a few hardcoded exceptions in html-minifier.

Also see https://stackoverflow.com/a/7854998/753676

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L71

```
// Empty Elements
var empty = makeMap('area,base,basefont,br,col,embed,frame,hr,img,input,isindex,keygen,link,meta,param,source,track,wbr');
```

https://github.com/kangax/html-minifier/blob/ce0e834891675f45dc60ab6128e61a0a25d0d199/src/htmlparser.js#L76-L78

```
// Elements that you can, intentionally, leave open
// (and which close themselves)
var closeSelf = makeMap('colgroup,dd,dt,li,option,p,td,tfoot,th,thead,tr,source');
```

So I would say it is not a bug and works as intended.

**Comment by DanielRuf** [comment] 2020-03-26 17:23
See https://github.com/kangax/html-minifier/issues/382 for the relevant issue.

**Comment by DanielRuf** [comment] 2020-03-26 17:27
To preserve ESI tags there are multiple ways:

https://github.com/kangax/html-minifier#ignoring-chunks-of-markup
`<!-- htmlmin:ignore -->`

> Ignoring chunks of markup
>
> If you have chunks of markup you would like preserved, you can wrap them `<!-- htmlmin:ignore -->`.

`ignoreCustomFragments`

> Array of regex'es that allow to ignore certain fragments, when matched (e.g. <?php ... ?>, {{ ... }}, etc.)

**Comment by DanielRuf** [comment] 2020-03-26 17:30
As this is no "valid" HTML code these are the only options in my opinion. Otherwise we would have to add more exceptions for any serverside solution and template language.

**Comment by jantimon** [comment] 2020-03-30 09:16
Cool think that's fine 👍

Didn't know about `<!-- htmlmin:ignore -->`

**Closed by jantimon** 2020-03-30 09:16 UTC
