### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined when used with webpack 5

### ISSUE THREAD

**Issue by Studio384** [jantimon/html-webpack-plugin#1282] opened 2019-09-27 09:34 UTC
## Expected behaviour

TypeError should not be thrown

## Current behaviour

TypeError is thrown

## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v10.15.3
win32 10.0.18363

npm --version
6.10.3

npm ls webpack
webpack@5.0.0-alpha.28

npm ls html-webpack-plugin
html-webpack-plugin@4.0.0-beta.8
```

### Config
```js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

const nodePathParts = ['./src', './node_modules'].map(p => path.resolve(p))

module.exports = {
  // https://github.com/webpack/changelog-v5/blob/master/README.md#persistent-caching
  cache: {
    type: 'filesystem'
  },
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, '/dist'),
    // filename: 'bundle.js'
    filename: 'bundle-[contenthash].js'
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    modules: nodePathParts
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  },
  plugins: [new HtmlWebpackPlugin()]
}
```

## Relevant Links

- #1163
- https://github.com/fengyun2/webpack5-demo

## Additional context

```
D:\webpack5-demo\node_modules\html-webpack-plugin\index.js:142
          compilation.compilationDependencies.add(fileDependency);
                                              ^

TypeError: Cannot read property 'add' of undefined
    at childCompilerDependencies.forEach.fileDependency (D:\test\js\20190214\webpack5-demo\node_modules\html-webpack-plugin\index.js:142:47)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalChunkAssets.tap (D:\test\js\20190214\webpack5-demo\node_modules\html-webpack-plugin\index.js:141:35)
    at SyncHook.eval [as call] (eval at create (D:\test\js\20190214\webpack5-demo\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (D:\test\js\20190214\webpack5-demo\node_modules\tapable\lib\Hook.js:154:20)
    at cont (D:\test\js\20190214\webpack5-demo\node_modules\webpack\lib\Compilation.js:1316:38)
    at createChunkAssets.err (D:\test\js\20190214\webpack5-demo\node_modules\webpack\lib\Compilation.js:1352:6)
    at D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2825:7
    at done (D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2861:11)
    at D:\test\js\20190214\webpack5-demo\node_modules\neo-async\async.js:2813:7
```

This is a duplicate for #1163 as reported by @fengyun2. I'm creating this issue again because I'm running into this with Webpack 5.0.0-alpha.28 and as mentioned in that closed and locked issue, it isn't a duplicate of #1129.

**Comment by thasmo** [comment] 2019-10-07 19:34
Having the same issue with webpack `5.0.0-alpha.30`.

**Comment by jantimon** [comment] 2020-03-24 09:40
Duplicate of #1129

**Closed by jantimon** 2020-03-24 09:40 UTC
